// src/components/customer-health/healthExerciseCatalogExpansion.js

function slugify(value = "") {
  return String(value)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function exercise(data) {
  const slug = data.slug || slugify(data.name);

  return {
    id: slug,
    slug,
    image: `/health/exercises/${slug}/${slug}-hero.png`,
    primary_muscles: [],
    secondary_muscles: [],
    equipment: "Bodyweight",
    location: "Anywhere",
    difficulty: "Intermediate",
    movement_pattern: "",
    category: "Strength",
    sets: "3",
    reps: "8-12",
    rest: "60-90 sec",
    feel: "",
    instructions: [],
    mistakes: [],
    safety: "",
    alternatives: [],
    variations: [],
    ...data,
  };
}

export const HEALTH_EXERCISE_CATALOG_EXPANSION = [
  exercise({
    name: "Conventional Deadlift",
    primary_muscles: ["Glutes", "Hamstrings", "Back"],
    secondary_muscles: ["Core", "Forearms"],
    equipment: "Barbell",
    location: "Gym",
    movement_pattern: "Hinge",
    sets: "3",
    reps: "3-8",
    rest: "120-180 sec",
    feel: "Legs drive the floor away while the torso stays braced.",
    instructions: ["Brace before pulling.", "Keep the bar close.", "Stand tall without leaning back."],
    mistakes: ["Jerking the bar", "Rounding the back", "Bar drifting forward"],
    safety: "Use a load you can control with a neutral spine.",
    alternatives: ["trap-bar-deadlift", "romanian-deadlift", "kettlebell-deadlift"],
    variations: ["sumo-deadlift", "pause-deadlift", "block-pull"],
  }),
  exercise({
    name: "Trap Bar Deadlift",
    primary_muscles: ["Glutes", "Quads", "Hamstrings"],
    secondary_muscles: ["Back", "Core", "Forearms"],
    equipment: "Trap bar",
    location: "Gym",
    movement_pattern: "Hinge",
    sets: "3",
    reps: "5-10",
    rest: "120-180 sec",
    feel: "Legs and hips driving upward with the load centered.",
    instructions: ["Stand centered in the bar.", "Brace and push through the floor.", "Finish tall."],
    mistakes: ["Hips shooting up", "Shrugging early", "Losing brace"],
    alternatives: ["conventional-deadlift", "leg-press", "kettlebell-deadlift"],
  }),
  exercise({
    name: "Goblet Squat",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Core"],
    equipment: "Dumbbell or kettlebell",
    location: "Gym or home",
    movement_pattern: "Squat",
    sets: "3",
    reps: "8-15",
    feel: "Quads and glutes working while the torso stays tall.",
    instructions: ["Hold the weight at the chest.", "Sit between the hips.", "Drive through the whole foot."],
    mistakes: ["Heels lifting", "Knees collapsing", "Losing posture"],
    alternatives: ["barbell-back-squat", "leg-press", "bodyweight-squat"],
  }),
  exercise({
    name: "Front Squat",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Core", "Upper back"],
    equipment: "Barbell and rack",
    location: "Gym",
    movement_pattern: "Squat",
    sets: "4",
    reps: "4-10",
    rest: "120-180 sec",
    feel: "Quads driving while the upper back keeps the torso upright.",
    instructions: ["Keep elbows high.", "Brace before descending.", "Drive straight up."],
    mistakes: ["Elbows dropping", "Heels lifting", "Knees collapsing"],
    alternatives: ["goblet-squat", "hack-squat", "leg-press"],
  }),
  exercise({
    name: "Hack Squat",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Hamstrings"],
    equipment: "Hack squat machine",
    location: "Gym",
    movement_pattern: "Squat",
    sets: "3",
    reps: "8-15",
    feel: "Quads and glutes driving through a supported path.",
    instructions: ["Set feet securely.", "Lower under control.", "Press without locking hard."],
    mistakes: ["Knees collapsing", "Bouncing", "Too-short range"],
    alternatives: ["leg-press", "goblet-squat", "barbell-back-squat"],
  }),
  exercise({
    name: "Bulgarian Split Squat",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Bench and dumbbells optional",
    location: "Gym or home",
    movement_pattern: "Lunge",
    sets: "3",
    reps: "8-12 each",
    feel: "Front leg doing most of the work.",
    instructions: ["Set the rear foot on a bench.", "Lower straight down.", "Drive through the front foot."],
    mistakes: ["Pushing off rear leg", "Knee collapsing", "Losing balance"],
    alternatives: ["reverse-lunge", "step-up", "split-squat"],
  }),
  exercise({
    name: "Reverse Lunge",
    primary_muscles: ["Glutes", "Quads"],
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight or dumbbells",
    location: "Anywhere",
    movement_pattern: "Lunge",
    sets: "3",
    reps: "8-12 each",
    feel: "Front glute and quad controlling the step.",
    instructions: ["Step back softly.", "Lower under control.", "Push through the front foot."],
    mistakes: ["Narrow stance", "Front knee collapsing", "Rushing"],
    alternatives: ["walking-lunge", "split-squat", "step-up"],
  }),
  exercise({
    name: "Walking Lunge",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight or dumbbells",
    location: "Gym or outdoors",
    movement_pattern: "Lunge",
    sets: "3",
    reps: "10-20 steps",
    feel: "Legs alternating under a stable torso.",
    instructions: ["Take a controlled step.", "Lower the rear knee.", "Drive into the next stride."],
    mistakes: ["Overstriding", "Knees collapsing", "Torso swaying"],
    alternatives: ["reverse-lunge", "step-up", "split-squat"],
  }),
  exercise({
    name: "Step-Up",
    primary_muscles: ["Glutes", "Quads"],
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Box or bench",
    location: "Gym or home",
    movement_pattern: "Step",
    sets: "3",
    reps: "8-12 each",
    feel: "Top leg lifting the body without jumping from the floor.",
    instructions: ["Place the whole foot on the box.", "Lean slightly forward.", "Stand using the top leg."],
    mistakes: ["Pushing off the floor", "Box too high", "Knee collapsing"],
    alternatives: ["reverse-lunge", "bulgarian-split-squat", "leg-press"],
  }),
  exercise({
    name: "Leg Extension",
    primary_muscles: ["Quads"],
    equipment: "Leg extension machine",
    location: "Gym",
    movement_pattern: "Knee extension",
    sets: "3",
    reps: "10-20",
    rest: "45-75 sec",
    feel: "Quads straightening the knee under control.",
    instructions: ["Align knee with machine pivot.", "Extend smoothly.", "Lower slowly."],
    mistakes: ["Swinging", "Slamming stack", "Seat misaligned"],
    alternatives: ["sissy-squat", "spanish-squat", "goblet-squat"],
  }),
  exercise({
    name: "Seated Leg Curl",
    primary_muscles: ["Hamstrings"],
    secondary_muscles: ["Calves"],
    equipment: "Seated leg curl machine",
    location: "Gym",
    movement_pattern: "Knee flexion",
    sets: "3",
    reps: "10-15",
    rest: "45-75 sec",
    feel: "Hamstrings pulling the pad down and back.",
    instructions: ["Lock hips into the seat.", "Curl fully.", "Return slowly."],
    mistakes: ["Hips lifting", "Rushing", "Partial range"],
    alternatives: ["lying-leg-curl", "stability-ball-leg-curl", "romanian-deadlift"],
  }),
  exercise({
    name: "Lying Leg Curl",
    primary_muscles: ["Hamstrings"],
    secondary_muscles: ["Calves"],
    equipment: "Lying leg curl machine",
    location: "Gym",
    movement_pattern: "Knee flexion",
    sets: "3",
    reps: "10-15",
    feel: "Hamstrings curling without the hips lifting.",
    instructions: ["Keep hips against pad.", "Curl smoothly.", "Control the return."],
    mistakes: ["Hips rising", "Back arching", "Stack slamming"],
    alternatives: ["seated-leg-curl", "stability-ball-leg-curl", "romanian-deadlift"],
  }),
  exercise({
    name: "Standing Calf Raise",
    primary_muscles: ["Calves"],
    equipment: "Machine or dumbbells",
    location: "Gym or home",
    movement_pattern: "Plantar flexion",
    sets: "4",
    reps: "10-20",
    rest: "45-75 sec",
    feel: "Calves lifting the heel through a full range.",
    instructions: ["Use a full stretch.", "Rise onto the ball of the foot.", "Pause at the top."],
    mistakes: ["Bouncing", "Short range", "Ankles rolling"],
    alternatives: ["seated-calf-raise", "single-leg-calf-raise"],
  }),
  exercise({
    name: "Seated Calf Raise",
    primary_muscles: ["Calves"],
    equipment: "Seated calf machine",
    location: "Gym",
    movement_pattern: "Plantar flexion",
    sets: "4",
    reps: "12-20",
    feel: "Lower calves working through a controlled stretch and squeeze.",
    instructions: ["Set pads above knees.", "Lower heels fully.", "Raise and pause."],
    mistakes: ["Bouncing", "Partial range", "Rushing"],
    alternatives: ["standing-calf-raise", "single-leg-calf-raise"],
  }),
  exercise({
    name: "Glute Bridge",
    primary_muscles: ["Glutes"],
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight",
    location: "Anywhere",
    movement_pattern: "Hip extension",
    sets: "3",
    reps: "12-20",
    feel: "Glutes lifting the hips without low-back pressure.",
    instructions: ["Plant feet near hips.", "Brace lightly.", "Squeeze glutes at the top."],
    mistakes: ["Back hyperextension", "Feet too far away", "Rushing"],
    alternatives: ["hip-thrust", "cable-pull-through"],
  }),
  exercise({
    name: "Cable Pull Through",
    primary_muscles: ["Glutes", "Hamstrings"],
    secondary_muscles: ["Core"],
    equipment: "Cable station and rope",
    location: "Gym",
    movement_pattern: "Hinge",
    sets: "3",
    reps: "10-15",
    feel: "Glutes and hamstrings driving the hips forward.",
    instructions: ["Face away from cable.", "Hinge hips back.", "Stand by squeezing glutes."],
    mistakes: ["Squatting", "Pulling with arms", "Back hyperextension"],
    alternatives: ["romanian-deadlift", "hip-thrust", "kettlebell-swing"],
  }),
  exercise({
    name: "Incline Barbell Press",
    primary_muscles: ["Upper chest"],
    secondary_muscles: ["Triceps", "Front shoulders"],
    equipment: "Barbell and incline bench",
    location: "Gym",
    movement_pattern: "Incline press",
    sets: "4",
    reps: "6-10",
    rest: "90-150 sec",
    feel: "Upper chest pressing while shoulder blades stay set.",
    instructions: ["Use a moderate incline.", "Lower to upper chest.", "Press without shrugging."],
    mistakes: ["Incline too steep", "Elbows flaring", "Bouncing"],
    alternatives: ["incline-dumbbell-press", "machine-incline-press"],
  }),
  exercise({
    name: "Close Grip Bench Press",
    primary_muscles: ["Triceps"],
    secondary_muscles: ["Chest", "Front shoulders"],
    equipment: "Barbell and bench",
    location: "Gym",
    movement_pattern: "Horizontal press",
    sets: "3",
    reps: "6-10",
    feel: "Triceps driving the bar with elbows controlled.",
    instructions: ["Use a shoulder-width grip.", "Keep elbows near ribs.", "Press smoothly."],
    mistakes: ["Grip too narrow", "Wrists bent", "Elbows flaring"],
    alternatives: ["rope-triceps-pushdown", "close-grip-push-up", "dip"],
  }),
  exercise({
    name: "Chest Dip",
    primary_muscles: ["Chest", "Triceps"],
    secondary_muscles: ["Front shoulders"],
    equipment: "Dip bars",
    location: "Gym",
    movement_pattern: "Vertical press",
    sets: "3",
    reps: "6-15",
    feel: "Chest and triceps pressing the body upward.",
    instructions: ["Lean slightly forward.", "Lower only as far as shoulders tolerate.", "Press without shrugging."],
    mistakes: ["Dropping too deep", "Shoulders rolling", "Swinging"],
    safety: "Avoid painful shoulder depth.",
    alternatives: ["machine-chest-press", "push-up", "close-grip-bench-press"],
  }),
  exercise({
    name: "Dumbbell Chest Fly",
    primary_muscles: ["Chest"],
    secondary_muscles: ["Front shoulders"],
    equipment: "Dumbbells and bench",
    location: "Gym or home",
    movement_pattern: "Chest isolation",
    sets: "3",
    reps: "10-15",
    feel: "Chest stretching and bringing the arms together.",
    instructions: ["Keep elbows softly bent.", "Lower in a wide arc.", "Stop before shoulder strain."],
    mistakes: ["Too much weight", "Straight elbows", "Overstretching"],
    alternatives: ["cable-chest-fly", "machine-fly"],
  }),
  exercise({
    name: "Assisted Pull-Up",
    primary_muscles: ["Lats", "Upper back"],
    secondary_muscles: ["Biceps"],
    equipment: "Assisted pull-up machine",
    location: "Gym",
    movement_pattern: "Vertical pull",
    sets: "3",
    reps: "6-12",
    feel: "Elbows driving down as the chest rises.",
    instructions: ["Set assistance.", "Pull elbows toward ribs.", "Lower fully."],
    mistakes: ["Kicking", "Shrugging", "Partial range"],
    alternatives: ["lat-pulldown", "band-assisted-pull-up"],
  }),
  exercise({
    name: "Pull-Up",
    primary_muscles: ["Lats", "Upper back"],
    secondary_muscles: ["Biceps", "Core"],
    equipment: "Pull-up bar",
    location: "Gym or home",
    movement_pattern: "Vertical pull",
    sets: "3",
    reps: "3-12",
    rest: "90-150 sec",
    feel: "Back pulling the elbows down toward the ribs.",
    instructions: ["Start from a controlled hang.", "Pull chest upward.", "Lower without dropping."],
    mistakes: ["Kipping", "Shrugging", "Half reps"],
    alternatives: ["assisted-pull-up", "lat-pulldown"],
  }),
  exercise({
    name: "Chest Supported Row",
    primary_muscles: ["Mid back", "Lats"],
    secondary_muscles: ["Biceps", "Rear shoulders"],
    equipment: "Bench and dumbbells or machine",
    location: "Gym",
    movement_pattern: "Horizontal pull",
    sets: "3",
    reps: "8-15",
    feel: "Upper back rowing without torso momentum.",
    instructions: ["Support chest firmly.", "Row elbows back.", "Pause and lower slowly."],
    mistakes: ["Shrugging", "Short range", "Jerking"],
    alternatives: ["seated-cable-row", "one-arm-dumbbell-row"],
  }),
  exercise({
    name: "T Bar Row",
    primary_muscles: ["Mid back", "Lats"],
    secondary_muscles: ["Biceps", "Rear shoulders"],
    equipment: "T-bar row",
    location: "Gym",
    movement_pattern: "Horizontal pull",
    sets: "3",
    reps: "6-12",
    feel: "Back pulling the handle toward the torso.",
    instructions: ["Brace the torso.", "Row toward lower chest.", "Control the return."],
    mistakes: ["Standing too upright", "Jerking", "Shrugging"],
    alternatives: ["chest-supported-row", "seated-cable-row"],
  }),
  exercise({
    name: "Face Pull",
    primary_muscles: ["Rear shoulders", "Upper back"],
    secondary_muscles: ["Rotator cuff"],
    equipment: "Cable station and rope",
    location: "Gym",
    movement_pattern: "Horizontal pull",
    sets: "3",
    reps: "12-20",
    rest: "45-60 sec",
    feel: "Rear shoulders and upper back pulling toward the face.",
    instructions: ["Set cable near eye level.", "Pull rope apart.", "Keep ribs down."],
    mistakes: ["Shrugging", "Leaning back", "Using too much weight"],
    alternatives: ["reverse-fly", "band-face-pull"],
  }),
  exercise({
    name: "Reverse Fly",
    primary_muscles: ["Rear shoulders"],
    secondary_muscles: ["Upper back"],
    equipment: "Dumbbells or machine",
    location: "Gym or home",
    movement_pattern: "Shoulder isolation",
    sets: "3",
    reps: "12-20",
    feel: "Rear delts opening the arms without shrugging.",
    instructions: ["Use light weight.", "Move arms wide.", "Pause briefly."],
    mistakes: ["Swinging", "Shrugging", "Too much elbow bend"],
    alternatives: ["face-pull", "reverse-pec-deck"],
  }),
  exercise({
    name: "Arnold Press",
    primary_muscles: ["Shoulders"],
    secondary_muscles: ["Triceps"],
    equipment: "Dumbbells",
    location: "Gym or home",
    movement_pattern: "Vertical press",
    sets: "3",
    reps: "8-12",
    feel: "Shoulders controlling rotation into the press.",
    instructions: ["Start palms facing in.", "Rotate smoothly.", "Press without arching."],
    mistakes: ["Rushing rotation", "Back arching", "Going too heavy"],
    alternatives: ["shoulder-press", "machine-shoulder-press"],
  }),
  exercise({
    name: "Machine Shoulder Press",
    primary_muscles: ["Shoulders"],
    secondary_muscles: ["Triceps"],
    equipment: "Shoulder press machine",
    location: "Gym",
    movement_pattern: "Vertical press",
    sets: "3",
    reps: "8-15",
    feel: "Shoulders pressing through a supported path.",
    instructions: ["Adjust seat.", "Keep ribs down.", "Press without shrugging."],
    mistakes: ["Seat too low", "Back arching", "Locking aggressively"],
    alternatives: ["shoulder-press", "landmine-press"],
  }),
  exercise({
    name: "Landmine Press",
    primary_muscles: ["Shoulders", "Upper chest"],
    secondary_muscles: ["Triceps", "Core"],
    equipment: "Landmine or anchored barbell",
    location: "Gym",
    movement_pattern: "Angled press",
    sets: "3",
    reps: "8-12 each",
    feel: "Shoulder pressing forward and up with stable ribs.",
    instructions: ["Brace the core.", "Press in the bar path.", "Avoid leaning back."],
    mistakes: ["Torso rotation", "Shrugging", "Rib flare"],
    alternatives: ["shoulder-press", "incline-dumbbell-press"],
  }),
  exercise({
    name: "Cable Lateral Raise",
    primary_muscles: ["Side shoulders"],
    equipment: "Cable station",
    location: "Gym",
    movement_pattern: "Shoulder isolation",
    sets: "3",
    reps: "12-20",
    rest: "45-60 sec",
    feel: "Side delt lifting against steady cable tension.",
    instructions: ["Stand tall.", "Lift slightly forward.", "Stop near shoulder height."],
    mistakes: ["Shrugging", "Swinging", "Too much weight"],
    alternatives: ["lateral-raise", "machine-lateral-raise"],
  }),
  exercise({
    name: "Hammer Curl",
    primary_muscles: ["Biceps", "Forearms"],
    equipment: "Dumbbells",
    location: "Gym or home",
    movement_pattern: "Elbow flexion",
    sets: "3",
    reps: "8-15",
    feel: "Arms curling with palms facing inward.",
    instructions: ["Keep elbows still.", "Curl without swinging.", "Lower slowly."],
    mistakes: ["Shoulder movement", "Swinging", "Dropping weight"],
    alternatives: ["dumbbell-biceps-curl", "cable-curl"],
  }),
  exercise({
    name: "Preacher Curl",
    primary_muscles: ["Biceps"],
    equipment: "Preacher bench and bar or dumbbell",
    location: "Gym",
    movement_pattern: "Elbow flexion",
    sets: "3",
    reps: "8-15",
    feel: "Biceps working with upper arms supported.",
    instructions: ["Set armpits near pad top.", "Curl smoothly.", "Avoid hard elbow lockout."],
    mistakes: ["Lifting shoulders", "Dropping bottom", "Too much weight"],
    alternatives: ["dumbbell-biceps-curl", "machine-curl"],
  }),
  exercise({
    name: "Cable Curl",
    primary_muscles: ["Biceps"],
    secondary_muscles: ["Forearms"],
    equipment: "Cable station",
    location: "Gym",
    movement_pattern: "Elbow flexion",
    sets: "3",
    reps: "10-15",
    feel: "Biceps curling against continuous tension.",
    instructions: ["Keep elbows near sides.", "Curl fully.", "Return slowly."],
    mistakes: ["Leaning back", "Elbows moving", "Rushing"],
    alternatives: ["dumbbell-biceps-curl", "preacher-curl"],
  }),
  exercise({
    name: "Skull Crusher",
    primary_muscles: ["Triceps"],
    equipment: "EZ bar or dumbbells and bench",
    location: "Gym",
    movement_pattern: "Elbow extension",
    sets: "3",
    reps: "8-15",
    feel: "Triceps extending the elbow from a stretched position.",
    instructions: ["Keep upper arms steady.", "Lower behind forehead.", "Extend smoothly."],
    mistakes: ["Elbows flaring", "Shoulders moving", "Too much weight"],
    alternatives: ["overhead-triceps-extension", "rope-triceps-pushdown"],
  }),
  exercise({
    name: "Pallof Press",
    primary_muscles: ["Core", "Obliques"],
    equipment: "Cable or resistance band",
    location: "Gym or home",
    movement_pattern: "Anti-rotation",
    sets: "3",
    reps: "10-15 each",
    feel: "Core resisting rotation as arms extend.",
    instructions: ["Stand perpendicular to resistance.", "Brace.", "Press hands forward without twisting."],
    mistakes: ["Rotating", "Leaning", "Holding breath"],
    alternatives: ["side-plank", "dead-bug"],
  }),
  exercise({
    name: "Dead Bug",
    primary_muscles: ["Core"],
    secondary_muscles: ["Hip flexors"],
    equipment: "Bodyweight",
    location: "Anywhere",
    movement_pattern: "Anti-extension",
    sets: "3",
    reps: "8-12 each",
    feel: "Abs keeping the low back controlled as limbs move.",
    instructions: ["Press low back gently down.", "Move opposite arm and leg.", "Exhale during extension."],
    mistakes: ["Back arching", "Rushing", "Moving too far"],
    alternatives: ["plank", "bird-dog"],
  }),
  exercise({
    name: "Side Plank",
    primary_muscles: ["Obliques", "Core"],
    secondary_muscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    location: "Anywhere",
    movement_pattern: "Anti-lateral flexion",
    sets: "3",
    reps: "20-45 sec each",
    feel: "Side core holding the hips in line.",
    instructions: ["Stack elbow under shoulder.", "Lift hips.", "Keep body straight."],
    mistakes: ["Hips sagging", "Shoulder shrugging", "Torso rotating"],
    alternatives: ["pallof-press", "suitcase-carry"],
  }),
  exercise({
    name: "Hanging Knee Raise",
    primary_muscles: ["Abs", "Hip flexors"],
    secondary_muscles: ["Forearms"],
    equipment: "Pull-up bar",
    location: "Gym",
    movement_pattern: "Trunk flexion",
    sets: "3",
    reps: "8-15",
    feel: "Abs curling the pelvis upward.",
    instructions: ["Hang with control.", "Lift knees.", "Tilt pelvis rather than only flexing hips."],
    mistakes: ["Swinging", "Using momentum", "Only lifting thighs"],
    alternatives: ["captains-chair-knee-raise", "reverse-crunch"],
  }),
  exercise({
    name: "Cable Crunch",
    primary_muscles: ["Abs"],
    equipment: "Cable station and rope",
    location: "Gym",
    movement_pattern: "Trunk flexion",
    sets: "3",
    reps: "10-20",
    feel: "Abs bringing ribs toward pelvis.",
    instructions: ["Keep hips mostly fixed.", "Crunch through the spine.", "Return under control."],
    mistakes: ["Sitting hips back", "Pulling with arms", "Rushing"],
    alternatives: ["reverse-crunch", "machine-crunch"],
  }),
  exercise({
    name: "Bird Dog",
    primary_muscles: ["Core", "Lower back"],
    secondary_muscles: ["Glutes", "Shoulders"],
    equipment: "Bodyweight",
    location: "Anywhere",
    category: "Mobility and strength",
    movement_pattern: "Spinal stability",
    sets: "3",
    reps: "8-12 each",
    feel: "Core preventing rotation as opposite limbs extend.",
    instructions: ["Start on hands and knees.", "Brace.", "Reach opposite arm and leg long."],
    mistakes: ["Back arching", "Hips rotating", "Moving too quickly"],
    alternatives: ["dead-bug", "plank"],
  }),
  exercise({
    name: "Bodyweight Squat",
    primary_muscles: ["Quads", "Glutes"],
    secondary_muscles: ["Core"],
    equipment: "Bodyweight",
    location: "Anywhere",
    movement_pattern: "Squat",
    sets: "3",
    reps: "12-25",
    feel: "Legs controlling the squat through a comfortable range.",
    instructions: ["Brace lightly.", "Sit down between hips.", "Stand through the whole foot."],
    mistakes: ["Heels lifting", "Knees collapsing", "Rushing"],
    alternatives: ["goblet-squat", "box-squat"],
  }),
  exercise({
    name: "Incline Push-Up",
    primary_muscles: ["Chest"],
    secondary_muscles: ["Triceps", "Shoulders", "Core"],
    equipment: "Bench or stable surface",
    location: "Anywhere",
    movement_pattern: "Horizontal press",
    sets: "3",
    reps: "8-20",
    feel: "Chest and triceps pressing with a rigid body.",
    instructions: ["Place hands on a stable surface.", "Keep body straight.", "Lower chest and press away."],
    mistakes: ["Hips sagging", "Elbows flaring", "Short range"],
    alternatives: ["push-up", "machine-chest-press"],
  }),
  exercise({
    name: "Band Row",
    primary_muscles: ["Mid back", "Lats"],
    secondary_muscles: ["Biceps"],
    equipment: "Resistance band",
    location: "Home or anywhere",
    movement_pattern: "Horizontal pull",
    sets: "3",
    reps: "12-20",
    feel: "Back pulling elbows toward the ribs.",
    instructions: ["Anchor band securely.", "Sit or stand tall.", "Row and pause."],
    mistakes: ["Shrugging", "Leaning back", "Rushing"],
    alternatives: ["seated-cable-row", "one-arm-dumbbell-row"],
  }),
  exercise({
    name: "Band Pull Apart",
    primary_muscles: ["Upper back", "Rear shoulders"],
    equipment: "Resistance band",
    location: "Anywhere",
    category: "Warm-up",
    movement_pattern: "Horizontal pull",
    sets: "2",
    reps: "15-25",
    rest: "30 sec",
    feel: "Upper back opening the arms without shrugging.",
    instructions: ["Hold band at chest height.", "Pull apart.", "Return slowly."],
    mistakes: ["Shrugging", "Back arching", "Using too much tension"],
    alternatives: ["face-pull", "reverse-fly"],
  }),
  exercise({
    name: "Treadmill Walk",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "Treadmill",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Steady state",
    sets: "1",
    reps: "10-45 min",
    rest: "As needed",
    feel: "Sustainable breathing and smooth walking mechanics.",
    instructions: ["Choose a comfortable speed.", "Use incline as tolerated.", "Keep posture tall."],
    mistakes: ["Holding rails heavily", "Starting too fast", "Overstriding"],
    alternatives: ["outdoor-walk", "elliptical", "stationary-bike"],
  }),
  exercise({
    name: "Incline Treadmill Walk",
    primary_muscles: ["Cardiovascular", "Glutes", "Calves"],
    equipment: "Treadmill",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Incline steady state",
    sets: "1",
    reps: "10-30 min",
    rest: "As needed",
    feel: "Glutes and calves working while breathing stays controlled.",
    instructions: ["Raise incline gradually.", "Keep steps short.", "Stay tall."],
    mistakes: ["Hanging on rails", "Incline too steep", "Leaning forward excessively"],
    alternatives: ["stair-climber", "outdoor-hill-walk", "elliptical"],
  }),
  exercise({
    name: "Outdoor Walk",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "None",
    location: "Outdoors",
    category: "Cardio",
    movement_pattern: "Steady state",
    sets: "1",
    reps: "15-60 min",
    rest: "As needed",
    feel: "Easy-to-moderate effort that supports recovery and daily movement.",
    instructions: ["Walk at a sustainable pace.", "Keep shoulders relaxed.", "Track time or distance."],
    mistakes: ["Starting too fast", "Ignoring pain", "Poor footwear"],
    alternatives: ["treadmill-walk", "stationary-bike", "elliptical"],
  }),
  exercise({
    name: "Outdoor Run",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "Running shoes",
    location: "Outdoors",
    category: "Cardio",
    movement_pattern: "Running",
    sets: "1",
    reps: "10-45 min",
    rest: "As needed",
    feel: "Rhythmic running at a pace matched to the training goal.",
    instructions: ["Warm up first.", "Use a sustainable stride.", "Cool down gradually."],
    mistakes: ["Too much pace too soon", "Overstriding", "Ignoring pain"],
    alternatives: ["treadmill-run", "elliptical", "stationary-bike"],
  }),
  exercise({
    name: "Treadmill Run",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "Treadmill",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Running",
    sets: "1",
    reps: "10-40 min",
    rest: "As needed",
    feel: "Controlled running rhythm with repeatable breathing.",
    instructions: ["Warm up with walking.", "Increase speed gradually.", "Use the safety clip."],
    mistakes: ["Jumping onto moving belt", "Starting too fast", "Holding rails"],
    alternatives: ["outdoor-run", "elliptical", "rowing-machine"],
  }),
  exercise({
    name: "Stationary Bike",
    primary_muscles: ["Cardiovascular", "Quads"],
    secondary_muscles: ["Glutes", "Hamstrings"],
    equipment: "Stationary bike",
    location: "Gym or home",
    category: "Cardio",
    movement_pattern: "Cycling",
    sets: "1",
    reps: "10-45 min",
    rest: "As needed",
    feel: "Smooth pedaling with a sustainable cadence.",
    instructions: ["Adjust seat height.", "Start easy.", "Add resistance gradually."],
    mistakes: ["Seat too low", "Rocking hips", "Grinding excessive resistance"],
    alternatives: ["recumbent-bike", "elliptical", "treadmill-walk"],
  }),
  exercise({
    name: "Recumbent Bike",
    primary_muscles: ["Cardiovascular", "Quads"],
    secondary_muscles: ["Glutes"],
    equipment: "Recumbent bike",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Cycling",
    sets: "1",
    reps: "10-45 min",
    rest: "As needed",
    feel: "Low-impact cycling with back support.",
    instructions: ["Adjust the seat.", "Keep knees tracking forward.", "Pedal smoothly."],
    mistakes: ["Seat too close", "Knees collapsing", "Excessive resistance"],
    alternatives: ["stationary-bike", "elliptical", "treadmill-walk"],
  }),
  exercise({
    name: "Elliptical",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "Elliptical machine",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Low-impact steady state",
    sets: "1",
    reps: "10-45 min",
    rest: "As needed",
    feel: "Smooth full-body rhythm without joint impact.",
    instructions: ["Start at low resistance.", "Keep posture tall.", "Push and pull handles smoothly."],
    mistakes: ["Leaning heavily", "Resistance too high", "Short choppy strides"],
    alternatives: ["stationary-bike", "treadmill-walk", "rowing-machine"],
  }),
  exercise({
    name: "Stair Climber",
    primary_muscles: ["Cardiovascular", "Glutes", "Quads"],
    secondary_muscles: ["Calves"],
    equipment: "Stair climber",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Climbing",
    sets: "1",
    reps: "5-30 min",
    rest: "As needed",
    feel: "Glutes and quads climbing with controlled breathing.",
    instructions: ["Start slowly.", "Place full foot on step.", "Stand tall."],
    mistakes: ["Leaning on rails", "Skipping steps without control", "Starting too fast"],
    alternatives: ["incline-treadmill-walk", "step-up", "elliptical"],
  }),
  exercise({
    name: "Rowing Machine",
    primary_muscles: ["Cardiovascular", "Back", "Legs"],
    secondary_muscles: ["Core", "Arms"],
    equipment: "Rowing ergometer",
    location: "Gym or home",
    category: "Cardio",
    movement_pattern: "Rowing",
    sets: "1",
    reps: "8-30 min",
    rest: "As needed",
    feel: "Leg drive followed by torso and arm pull.",
    instructions: ["Push with legs first.", "Lean back slightly.", "Finish with handle near ribs."],
    mistakes: ["Pulling arms first", "Rounding back", "Rushing recovery"],
    alternatives: ["elliptical", "stationary-bike", "ski-erg"],
  }),
  exercise({
    name: "Ski Erg",
    primary_muscles: ["Cardiovascular", "Lats", "Core"],
    secondary_muscles: ["Triceps", "Legs"],
    equipment: "Ski ergometer",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Ski pull",
    sets: "1",
    reps: "8-25 min",
    rest: "As needed",
    feel: "Lats and core driving the handles downward.",
    instructions: ["Start tall.", "Hinge slightly.", "Drive handles toward hips."],
    mistakes: ["Only using arms", "Back rounding", "Starting too hard"],
    alternatives: ["rowing-machine", "elliptical", "battle-ropes"],
  }),
  exercise({
    name: "Jump Rope",
    primary_muscles: ["Cardiovascular", "Calves"],
    secondary_muscles: ["Shoulders", "Core"],
    equipment: "Jump rope",
    location: "Gym or outdoors",
    category: "Cardio",
    movement_pattern: "Jumping",
    sets: "5",
    reps: "30-90 sec",
    rest: "30-60 sec",
    feel: "Light rhythmic jumps with relaxed shoulders.",
    instructions: ["Keep jumps low.", "Turn rope with wrists.", "Land softly."],
    mistakes: ["Jumping too high", "Tensing shoulders", "Landing heavily"],
    alternatives: ["march-in-place", "bike-intervals", "low-impact-jacks"],
  }),
  exercise({
    name: "Battle Ropes",
    primary_muscles: ["Cardiovascular", "Shoulders", "Arms"],
    secondary_muscles: ["Core", "Legs"],
    equipment: "Battle ropes",
    location: "Gym",
    category: "Cardio",
    movement_pattern: "Intervals",
    sets: "6",
    reps: "20-40 sec",
    rest: "40-60 sec",
    feel: "Fast upper-body effort while the lower body stays braced.",
    instructions: ["Use an athletic stance.", "Create consistent waves.", "Breathe throughout."],
    mistakes: ["Standing too upright", "Holding breath", "Losing rhythm"],
    alternatives: ["rowing-machine", "ski-erg", "bike-intervals"],
  }),
  exercise({
    name: "Bike Intervals",
    primary_muscles: ["Cardiovascular", "Quads"],
    secondary_muscles: ["Glutes", "Hamstrings"],
    equipment: "Stationary bike",
    location: "Gym or home",
    category: "HIIT",
    movement_pattern: "Intervals",
    sets: "8",
    reps: "20-40 sec hard",
    rest: "60-100 sec easy",
    feel: "Repeatable hard efforts without losing pedaling control.",
    instructions: ["Warm up first.", "Push hard for the work period.", "Recover at easy resistance."],
    mistakes: ["Skipping warm-up", "Maxing every round", "Poor seat setup"],
    alternatives: ["rower-intervals", "treadmill-intervals", "battle-ropes"],
  }),
  exercise({
    name: "Rower Intervals",
    primary_muscles: ["Cardiovascular", "Legs", "Back"],
    secondary_muscles: ["Core", "Arms"],
    equipment: "Rowing ergometer",
    location: "Gym",
    category: "HIIT",
    movement_pattern: "Intervals",
    sets: "6",
    reps: "30-60 sec hard",
    rest: "60-120 sec easy",
    feel: "Powerful leg drive repeated with controlled technique.",
    instructions: ["Warm up.", "Drive with legs.", "Keep stroke quality consistent."],
    mistakes: ["Arms pulling first", "Technique collapsing", "Starting too hard"],
    alternatives: ["bike-intervals", "ski-erg", "treadmill-intervals"],
  }),
  exercise({
    name: "Treadmill Intervals",
    primary_muscles: ["Cardiovascular", "Legs"],
    equipment: "Treadmill",
    location: "Gym",
    category: "HIIT",
    movement_pattern: "Intervals",
    sets: "6",
    reps: "30-90 sec hard",
    rest: "60-120 sec easy",
    feel: "Fast but controlled running with full recovery between rounds.",
    instructions: ["Warm up thoroughly.", "Use safe speed changes.", "Recover with walking."],
    mistakes: ["Unsafe speed jumps", "Holding rails", "Skipping recovery"],
    safety: "Use the safety clip and choose speeds you can enter and exit safely.",
    alternatives: ["bike-intervals", "rower-intervals", "outdoor-run"],
  }),
];
