import React, { useEffect, useMemo, useState } from "react";
import api from "../../api/client";
import Button from "../ui/Button";

const inputClass = "min-h-10 w-full rounded-xl border border-slate-700 bg-black/35 px-3 py-2 text-sm text-white outline-none focus:border-cyan-400/70";
const money = (v) => Number(v || 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
const today = new Date().toISOString().slice(0, 10);
const blankRule = () => ({ id: `rule-${Date.now()}`, label: "Late fee", mode: "FIXED_DAY", trigger: 5, amount: "50.00", monthly_cap: "0.00", enabled: true });
const advancedDefaults = { late_fee_rules: [], payment_arrangement_enabled: false, payment_arrangement_frequency: "BIWEEKLY", payment_arrangement_amount: "0.00", payment_arrangement_start: "", payment_arrangement_end: "", pause_late_fees_during_arrangement: true, collection_status: "NONE", collection_start_date: "", collection_monthly_late_fee_cap: "0.00", eviction_filed: false, eviction_filed_date: "", stop_late_fees_after_eviction: false, move_out_date: "", prorate_final_month: false, deposit_required: "0.00", deposit_received: "0.00", deposit_held: "0.00", deposit_applied: "0.00", deposit_notes: "", collections_recipient_name: "", collections_recipient_email: "", collections_notes: "" };
const payerDefaults = { payer_split_enabled: false, installment_schedule_enabled: false, installment_frequency: "BIWEEKLY", installment_anchor_date: "", installment_amount: "0.00", installment_grace_days: 0, installment_late_fee_amount: "50.00" };

function Field({ label, children }) { return <label className="block"><span className="mb-1 block text-[11px] font-semibold text-slate-300">{label}</span>{children}</label>; }
function Section({ step, title, subtitle, open, onClick, children, badge, warning }) {
  return <section className={`overflow-hidden rounded-2xl border ${open ? "border-cyan-400/35 bg-[#081524]" : "border-slate-800 bg-[#07111f]"}`}>
    <button type="button" onClick={onClick} className="flex w-full items-center gap-3 p-3 text-left hover:bg-white/[.02]">
      <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-[10px] font-black ${open ? "bg-cyan-400 text-slate-950" : "bg-slate-800 text-slate-300"}`}>{step}</span>
      <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><div className="text-sm font-black text-white">{title}</div>{warning ? <span className="rounded-full bg-amber-500/10 px-2 py-0.5 text-[9px] font-black text-amber-200">{warning}</span> : null}</div><div className="mt-0.5 text-[11px] text-slate-500">{subtitle}</div></div>
      <div className="flex shrink-0 items-center gap-2">{badge}<span className="text-sm font-black text-cyan-200">{open ? "Hide" : "Open"}</span><span className="text-base text-slate-400">{open ? "−" : "+"}</span></div>
    </button>
    {open ? <div className="border-t border-slate-800 p-3 sm:p-4">{children}</div> : null}
  </section>;
}
function errText(e, fallback) { return e?.response?.data?.detail || e?.response?.data?.reason || e?.message || fallback; }

export default function PMBillingPolicyEditor({ workspace, tenant, onRefresh }) {
  const tenantId = tenant?.id;
  const headers = useMemo(() => workspace?.id ? { "X-PM-Workspace-ID": String(workspace.id) } : {}, [workspace?.id]);
  const [open, setOpen] = useState("rent");
  const [payer, setPayer] = useState(payerDefaults);
  const [advanced, setAdvanced] = useState(advancedDefaults);
  const [allocation, setAllocation] = useState({ contract_rent: "0.00", tenant_portion: "0.00", housing_portion: "0.00", section8: false });
  const [history, setHistory] = useState([]);
  const [deposit, setDeposit] = useState({ required: "0.00", received: "0.00", held: "0.00", applied: "0.00", remaining: "0.00" });
  const [company, setCompany] = useState({ exists: false, template: {} });
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [rentChange, setRentChange] = useState({ reason_type: "CORRECTION", reason: "", document_pending: false, file: null });
  const [depositUse, setDepositUse] = useState({ amount: "", apply_to: "RENT", entry_date: today, memo: "" });
  const toggle = (key) => setOpen((current) => current === key ? "" : key);
  const ppatch = (key, value) => setPayer((x) => ({ ...x, [key]: value }));
  const apatch = (key, value) => setAdvanced((x) => ({ ...x, [key]: value }));

  async function load() {
    if (!tenantId || !workspace) return;
    setError("");
    try {
      const [p, a, r, d, c] = await Promise.all([
        api.get(`/pm-hub/billing/tenants/${tenantId}/payer-profile/`, { headers }),
        api.get(`/pm-hub/billing/tenants/${tenantId}/advanced/`, { headers }),
        api.get(`/pm-hub/billing/tenants/${tenantId}/rent-allocation/`, { headers }),
        api.get(`/pm-hub/billing/tenants/${tenantId}/deposit-status/`, { headers }),
        api.get(`/pm-hub/billing/company-template/`, { headers }),
      ]);
      setPayer({ ...payerDefaults, ...(p.data?.profile || {}) });
      setAdvanced({ ...advancedDefaults, ...(a.data?.profile || {}), late_fee_rules: a.data?.profile?.late_fee_rules || [] });
      setAllocation(r.data?.allocation || {}); setHistory(r.data?.history || []); setDeposit(d.data || {}); setCompany(c.data || { exists: false, template: {} });
    } catch (e) { setError(errText(e, "Could not load lease and billing rules.")); }
  }
  useEffect(() => { load(); }, [tenantId, workspace?.id]);

  async function run(fn, success) { setBusy(true); setError(""); setMessage(""); try { await fn(); setMessage(success); await load(); onRefresh?.(); } catch (e) { setError(errText(e, "Could not save changes.")); } finally { setBusy(false); } }
  const savePayer = () => run(() => api.patch(`/pm-hub/billing/tenants/${tenantId}/payer-profile/`, { ...payer, workspace_id: workspace.id }, { headers }), "Payment schedule saved for this tenant.");
  const saveAdvanced = (label = "Lease-specific rules saved.") => run(() => api.patch(`/pm-hub/billing/tenants/${tenantId}/advanced/`, { ...advanced, workspace_id: workspace.id }, { headers }), label);
  const saveCompany = () => { const payload = { late_fee_rules: advanced.late_fee_rules, payment_arrangement_frequency: advanced.payment_arrangement_frequency, pause_late_fees_during_arrangement: advanced.pause_late_fees_during_arrangement, collection_monthly_late_fee_cap: advanced.collection_monthly_late_fee_cap, stop_late_fees_after_eviction: advanced.stop_late_fees_after_eviction, payer_split_enabled: payer.payer_split_enabled, installment_schedule_enabled: payer.installment_schedule_enabled, installment_frequency: payer.installment_frequency, installment_grace_days: payer.installment_grace_days, installment_late_fee_amount: payer.installment_late_fee_amount }; return run(() => api.patch(`/pm-hub/billing/company-template/`, payload, { headers }), "Company billing template saved. Existing leases were not changed."); };
  const applyCompany = () => run(() => api.post(`/pm-hub/billing/tenants/${tenantId}/apply-company-template/`, { workspace_id: workspace.id }, { headers }), "Company template applied to this tenant. Review tenant-specific exceptions.");
  const generateLate = () => run(() => api.post(`/pm-hub/billing/tenants/${tenantId}/generate-advanced-late-fees/`, { workspace_id: workspace.id, through_date: today }, { headers }), "Applicable lease late fees generated.");
  const generateInstallment = () => run(() => api.post(`/pm-hub/billing/tenants/${tenantId}/generate-installment-late-fees/`, { workspace_id: workspace.id, through_date: today }, { headers }), "Missed installment late fees generated.");
  const rebuildSplit = () => run(() => api.post(`/pm-hub/billing/tenants/${tenantId}/rebuild-split-rent/`, { workspace_id: workspace.id, start_date: payer.installment_anchor_date || today, through_date: today }, { headers }), "Generated rent charges rebuilt into Tenant and Housing buckets.");

  async function saveRent() {
    if (!rentChange.reason.trim()) return setError("Add a short reason for the rent change.");
    setBusy(true); setError(""); setMessage("");
    try {
      let documentId = null;
      if (rentChange.file) {
        if (!tenant?.property_id) throw new Error("This tenant must be linked to a property before supporting lease paperwork can be uploaded here.");
        const form = new FormData(); form.append("property", tenant.property_id); form.append("tenant", tenantId); form.append("category", "LEASE_ADDENDUM"); form.append("title", `Rent change support — ${tenant.full_name || "Tenant"}`); form.append("status", "SIGNED"); form.append("document", rentChange.file); form.append("notes", rentChange.reason);
        const doc = await api.post("/pm-hub/property-documents/", form, { headers: { ...headers, "Content-Type": "multipart/form-data" } }); documentId = doc.data?.id || null;
      }
      const response = await api.patch(`/pm-hub/billing/tenants/${tenantId}/rent-allocation/`, { ...allocation, reason_type: rentChange.reason_type, reason: rentChange.reason, supporting_document_id: documentId, document_pending: rentChange.reason_type === "LEASE_CHANGE" && !documentId ? rentChange.document_pending : false, workspace_id: workspace.id }, { headers });
      setMessage(response.data?.documentation_required && response.data?.document_pending ? "Rent updated. Supporting lease paperwork is flagged as pending." : "Rent allocation updated and change history recorded.");
      setRentChange({ reason_type: "CORRECTION", reason: "", document_pending: false, file: null }); await load(); onRefresh?.();
    } catch (e) { setError(errText(e, "Could not update rent allocation.")); } finally { setBusy(false); }
  }
  const applyDeposit = () => { if (!depositUse.amount) return setError("Enter the amount of deposit to apply."); return run(() => api.post(`/pm-hub/billing/tenants/${tenantId}/apply-deposit/`, { ...depositUse, workspace_id: workspace.id }, { headers }), "Deposit applied and ledger credit created."); };
  const updateRule = (i, key, value) => setAdvanced((x) => ({ ...x, late_fee_rules: x.late_fee_rules.map((r, n) => n === i ? { ...r, [key]: value } : r) }));

  if (!tenantId) return <div className="rounded-xl border border-amber-500/30 p-3 text-sm text-amber-100">Choose a tenant first.</div>;

  const depositStatus = Number(deposit.applied || 0) > 0 ? "APPLIED" : Number(deposit.received || 0) > 0 ? "COLLECTED" : "NOT COLLECTED";
  const arrangementBadge = advanced.payment_arrangement_enabled ? "ACTIVE" : "OFF";
  const collectionsBadge = advanced.collection_status && advanced.collection_status !== "NONE" ? advanced.collection_status : "NONE";

  return <div className="space-y-2.5 pb-6">
    {error ? <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-100">{error}</div> : null}
    {message ? <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-100">{message}</div> : null}

    <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-3">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-black">{tenant.full_name || "Tenant"}</div><div className="mt-0.5 text-[11px] text-slate-500">Open one section at a time. Tenant-specific rules override company defaults.</div></div><div className="flex flex-wrap gap-2"><button onClick={applyCompany} disabled={busy} className="rounded-lg border border-slate-600 bg-slate-800 px-2.5 py-1.5 text-[11px] font-black text-white disabled:opacity-40">Apply Company Template</button><button onClick={saveCompany} disabled={busy} className="rounded-lg border border-fuchsia-400/50 bg-fuchsia-500/15 px-2.5 py-1.5 text-[11px] font-black text-fuchsia-100 disabled:opacity-40">Save as Company Template</button></div></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-lg border border-slate-800 p-2.5"><div className="text-[10px] text-slate-500">Contract rent</div><div className="text-sm font-black">{money(allocation.contract_rent)}</div></div><div className="rounded-lg border border-slate-800 p-2.5"><div className="text-[10px] text-slate-500">Installment</div><div className="text-sm font-black">{payer.installment_schedule_enabled ? money(payer.installment_amount) : "Not scheduled"}</div></div><div className="rounded-lg border border-slate-800 p-2.5"><div className="text-[10px] text-slate-500">Deposit</div><div className="text-sm font-black">{depositStatus}</div></div><div className="rounded-lg border border-slate-800 p-2.5"><div className="text-[10px] text-slate-500">Late-fee rules</div><div className="text-sm font-black">{advanced.late_fee_rules.length}</div></div></div>
    </div>

    <Section step="1" title="Rent & payer split" subtitle="Contract rent, tenant share, Housing share, and audited rent changes." open={open === "rent"} onClick={() => toggle("rent")} badge={<span className="text-[11px] font-black text-cyan-300">{money(allocation.contract_rent)}</span>}>
      <div className="grid gap-3 md:grid-cols-3"><Field label="Contract rent"><input className={inputClass} value={allocation.contract_rent || ""} onChange={(e) => setAllocation((x) => ({ ...x, contract_rent: e.target.value }))}/></Field><Field label="Tenant portion"><input className={inputClass} value={allocation.tenant_portion || ""} onChange={(e) => setAllocation((x) => ({ ...x, tenant_portion: e.target.value }))}/></Field><Field label="Housing portion"><input className={inputClass} value={allocation.housing_portion || ""} onChange={(e) => setAllocation((x) => ({ ...x, housing_portion: e.target.value }))}/></Field></div>
      <div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Why are these amounts changing?"><select className={inputClass} value={rentChange.reason_type} onChange={(e) => setRentChange((x) => ({ ...x, reason_type: e.target.value }))}><option value="CORRECTION">Data correction / entry error</option><option value="LEASE_CHANGE">Lease or approved rent change</option></select></Field><Field label="Reason / notes"><input className={inputClass} value={rentChange.reason} onChange={(e) => setRentChange((x) => ({ ...x, reason: e.target.value }))} placeholder="Example: Corrected amount from signed lease"/></Field></div>
      {rentChange.reason_type === "LEASE_CHANGE" ? <div className="mt-3 rounded-xl border border-amber-500/25 bg-amber-500/5 p-3"><div className="text-xs font-black text-amber-100">Supporting paperwork required</div><div className="mt-2 grid gap-3 md:grid-cols-2"><input type="file" accept=".pdf,.jpg,.jpeg,.png" className={inputClass} onChange={(e) => setRentChange((x) => ({ ...x, file: e.target.files?.[0] || null }))}/><label className="flex items-center gap-2 rounded-xl border border-slate-700 px-3 text-xs"><input type="checkbox" checked={rentChange.document_pending} onChange={(e) => setRentChange((x) => ({ ...x, document_pending: e.target.checked }))}/>Paperwork will be uploaded later</label></div></div> : null}
      <div className="mt-3 flex flex-wrap gap-2"><Button tone="cyan" onClick={saveRent} disabled={busy}>Save Rent Change</Button><Button tone="slate" onClick={rebuildSplit} disabled={busy}>Rebuild Split Rent</Button></div>
    </Section>

    <Section step="2" title="Payment schedule" subtitle="Tenant installment timing and Section 8 payer split." open={open === "schedule"} onClick={() => toggle("schedule")} badge={<span className="text-[11px] text-slate-300">{payer.installment_schedule_enabled ? payer.installment_frequency : "Off"}</span>}>
      <div className="grid gap-3 md:grid-cols-2"><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-xs"><input type="checkbox" checked={Boolean(payer.payer_split_enabled)} onChange={(e) => ppatch("payer_split_enabled", e.target.checked)}/>Split rent into Tenant + Housing buckets</label><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-xs"><input type="checkbox" checked={Boolean(payer.installment_schedule_enabled)} onChange={(e) => ppatch("installment_schedule_enabled", e.target.checked)}/>Use tenant installment schedule</label><Field label="Frequency"><select className={inputClass} value={payer.installment_frequency || "BIWEEKLY"} onChange={(e) => ppatch("installment_frequency", e.target.value)}><option value="WEEKLY">Weekly</option><option value="BIWEEKLY">Every 2 weeks</option></select></Field><Field label="First installment due"><input type="date" className={inputClass} value={payer.installment_anchor_date || ""} onChange={(e) => ppatch("installment_anchor_date", e.target.value)}/></Field><Field label="Installment amount"><input className={inputClass} value={payer.installment_amount || "0.00"} onChange={(e) => ppatch("installment_amount", e.target.value)}/></Field><Field label="Grace days"><input type="number" className={inputClass} value={payer.installment_grace_days ?? 0} onChange={(e) => ppatch("installment_grace_days", e.target.value)}/></Field><Field label="Late fee"><input className={inputClass} value={payer.installment_late_fee_amount || "50.00"} onChange={(e) => ppatch("installment_late_fee_amount", e.target.value)}/></Field></div>
      <div className="mt-3 flex flex-wrap gap-2"><Button tone="cyan" onClick={savePayer} disabled={busy}>Save This Tenant</Button><Button tone="slate" onClick={generateInstallment} disabled={busy}>Generate Missed Late Fees</Button></div>
    </Section>

    <Section step="3" title="Late-fee rules" subtitle="Lease-specific checkpoints or daily rules." open={open === "late"} onClick={() => toggle("late")} badge={<span className="text-[11px] font-black text-fuchsia-300">{advanced.late_fee_rules.length} rules</span>}>
      <div className="space-y-2">{advanced.late_fee_rules.map((r, i) => <div key={r.id || i} className="grid gap-2 rounded-xl border border-slate-800 p-3 md:grid-cols-6"><Field label="Rule"><input className={inputClass} value={r.label || ""} onChange={(e) => updateRule(i, "label", e.target.value)}/></Field><Field label="Type"><select className={inputClass} value={r.mode || "FIXED_DAY"} onChange={(e) => updateRule(i, "mode", e.target.value)}><option value="FIXED_DAY">Day of month</option><option value="DAYS_LATE">Days after due</option><option value="DAILY">Daily after X days</option></select></Field><Field label="Trigger"><input type="number" className={inputClass} value={r.trigger || 1} onChange={(e) => updateRule(i, "trigger", e.target.value)}/></Field><Field label="Fee"><input className={inputClass} value={r.amount || "0.00"} onChange={(e) => updateRule(i, "amount", e.target.value)}/></Field><Field label="Monthly cap"><input className={inputClass} value={r.monthly_cap || "0.00"} onChange={(e) => updateRule(i, "monthly_cap", e.target.value)}/></Field><div className="flex items-end gap-2"><label className="flex min-h-10 flex-1 items-center gap-2 rounded-xl border border-slate-700 px-2 text-[11px]"><input type="checkbox" checked={r.enabled !== false} onChange={(e) => updateRule(i, "enabled", e.target.checked)}/>Active</label><button className="min-h-10 rounded-xl border border-rose-500/40 bg-rose-500/10 px-2 text-[11px] font-black text-rose-200" onClick={() => setAdvanced((x) => ({ ...x, late_fee_rules: x.late_fee_rules.filter((_, n) => n !== i) }))}>Delete</button></div></div>)}</div>
      <div className="mt-3 flex flex-wrap gap-2"><Button tone="slate" onClick={() => setAdvanced((x) => ({ ...x, late_fee_rules: [...x.late_fee_rules, blankRule()] }))}>+ Add Fee Rule</Button><Button tone="cyan" onClick={() => saveAdvanced("Late-fee rules saved and reloaded for this tenant.")} disabled={busy}>Save This Tenant</Button><Button tone="purple" onClick={saveCompany} disabled={busy}>Save as Company Template</Button><Button tone="slate" onClick={generateLate} disabled={busy}>Generate Applicable Fees</Button></div>
    </Section>

    <Section step="4" title="Payment arrangement" subtitle="Temporary payment plan for this tenant." open={open === "arrangement"} onClick={() => toggle("arrangement")} badge={<span className={`text-[11px] font-black ${advanced.payment_arrangement_enabled ? "text-emerald-300" : "text-slate-500"}`}>{arrangementBadge}</span>}>
      <div className="grid gap-3 md:grid-cols-2"><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-xs"><input type="checkbox" checked={advanced.payment_arrangement_enabled} onChange={(e) => apatch("payment_arrangement_enabled", e.target.checked)}/>Temporary payment arrangement</label><Field label="Amount"><input className={inputClass} value={advanced.payment_arrangement_amount} onChange={(e) => apatch("payment_arrangement_amount", e.target.value)}/></Field><Field label="Starts"><input type="date" className={inputClass} value={advanced.payment_arrangement_start} onChange={(e) => apatch("payment_arrangement_start", e.target.value)}/></Field><Field label="Ends"><input type="date" className={inputClass} value={advanced.payment_arrangement_end} onChange={(e) => apatch("payment_arrangement_end", e.target.value)}/></Field><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-xs"><input type="checkbox" checked={advanced.pause_late_fees_during_arrangement} onChange={(e) => apatch("pause_late_fees_during_arrangement", e.target.checked)}/>Pause other late fees during arrangement</label></div><div className="mt-3"><Button tone="cyan" onClick={() => saveAdvanced("Payment arrangement saved for this tenant.")} disabled={busy}>Save This Tenant</Button></div>
    </Section>

    <Section step="5" title="Security deposit" subtitle="See what was received, held, and applied." open={open === "deposit"} onClick={() => toggle("deposit")} badge={<span className={`text-[11px] font-black ${depositStatus === "APPLIED" ? "text-amber-300" : depositStatus === "COLLECTED" ? "text-emerald-300" : "text-slate-500"}`}>{depositStatus}</span>}>
      <div className="grid gap-2 sm:grid-cols-5">{[["Required", deposit.required], ["Received", deposit.received], ["Held", deposit.held], ["Applied", deposit.applied], ["Remaining", deposit.remaining]].map(([l, v]) => <div key={l} className="rounded-xl border border-slate-800 p-2.5"><div className="text-[10px] text-slate-500">{l}</div><div className="text-sm font-black">{money(v)}</div></div>)}</div>
      <div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Apply amount"><input className={inputClass} value={depositUse.amount} onChange={(e) => setDepositUse((x) => ({ ...x, amount: e.target.value }))}/></Field><Field label="Apply toward"><select className={inputClass} value={depositUse.apply_to} onChange={(e) => setDepositUse((x) => ({ ...x, apply_to: e.target.value }))}><option value="RENT">Rent</option><option value="DAMAGES">Damages</option><option value="LATE_FEE">Late fees</option><option value="UTILITY">Utilities</option><option value="BALANCE">General balance</option></select></Field><Field label="Date"><input type="date" className={inputClass} value={depositUse.entry_date} onChange={(e) => setDepositUse((x) => ({ ...x, entry_date: e.target.value }))}/></Field><Field label="Memo"><input className={inputClass} value={depositUse.memo} onChange={(e) => setDepositUse((x) => ({ ...x, memo: e.target.value }))}/></Field></div><div className="mt-3"><Button tone="cyan" onClick={applyDeposit} disabled={busy}>Apply Deposit & Create Credit</Button></div>
    </Section>

    <Section step="6" title="Collections & eviction" subtitle="Collections status, recipient, fee caps, move-out, and eviction controls." open={open === "collections"} onClick={() => toggle("collections")} badge={<span className={`text-[11px] font-black ${collectionsBadge === "NONE" ? "text-slate-500" : "text-amber-300"}`}>{collectionsBadge}</span>}>
      <div className="grid gap-3 md:grid-cols-2"><Field label="Collections status"><select className={inputClass} value={advanced.collection_status} onChange={(e) => apatch("collection_status", e.target.value)}><option value="NONE">Not in collections</option><option value="PREPARING">Preparing ledger</option><option value="SENT">Sent to collections</option><option value="LEGAL">Legal / eviction</option></select></Field><Field label="Collections start"><input type="date" className={inputClass} value={advanced.collection_start_date} onChange={(e) => apatch("collection_start_date", e.target.value)}/></Field><Field label="Monthly late-fee cap"><input className={inputClass} value={advanced.collection_monthly_late_fee_cap} onChange={(e) => apatch("collection_monthly_late_fee_cap", e.target.value)}/></Field><Field label="Move-out date"><input type="date" className={inputClass} value={advanced.move_out_date} onChange={(e) => apatch("move_out_date", e.target.value)}/></Field><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-xs"><input type="checkbox" checked={advanced.eviction_filed} onChange={(e) => apatch("eviction_filed", e.target.checked)}/>Eviction filed</label><Field label="Eviction filed date"><input type="date" className={inputClass} value={advanced.eviction_filed_date} onChange={(e) => apatch("eviction_filed_date", e.target.value)}/></Field><Field label="Recipient / firm"><input className={inputClass} value={advanced.collections_recipient_name} onChange={(e) => apatch("collections_recipient_name", e.target.value)}/></Field><Field label="Recipient email"><input type="email" className={inputClass} value={advanced.collections_recipient_email} onChange={(e) => apatch("collections_recipient_email", e.target.value)}/></Field><Field label="Notes"><textarea className={inputClass} rows={3} value={advanced.collections_notes} onChange={(e) => apatch("collections_notes", e.target.value)}/></Field></div><div className="mt-3"><Button tone="cyan" onClick={() => saveAdvanced("Collections and eviction settings saved.")} disabled={busy}>Save This Tenant</Button></div>
    </Section>

    <Section step="7" title="Company template" subtitle="Save reusable defaults without overwriting tenant-specific balances or case history." open={open === "company"} onClick={() => toggle("company")} badge={<span className={`text-[11px] font-black ${company.exists ? "text-emerald-300" : "text-slate-500"}`}>{company.exists ? "SAVED" : "NOT SET"}</span>}>
      <p className="text-xs text-slate-400">Save common policy here, then apply it to a tenant and adjust only that lease's exceptions.</p><div className="mt-3 flex flex-wrap gap-2"><Button tone="purple" onClick={saveCompany} disabled={busy}>Save Current Rules as Company Template</Button><Button tone="slate" onClick={applyCompany} disabled={busy}>Apply Template to This Tenant</Button></div>
    </Section>

    <Section step="8" title="Change history" subtitle="Audit trail for rent and payer changes." open={open === "history"} onClick={() => toggle("history")} badge={<span className="text-[11px] text-slate-400">{history.length} records</span>}>
      <div className="space-y-2">{history.length ? history.map((h, i) => <div key={h.id || i} className="rounded-xl border border-slate-800 p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><strong>{h.reason_type === "LEASE_CHANGE" ? "Lease / rent change" : "Data correction"}</strong><span className="text-[10px] text-slate-500">{String(h.changed_at || h.created_at || "").replace("T", " ").slice(0, 19)}</span></div><div className="mt-1 text-slate-400">{h.reason}</div><div className="mt-2 text-[10px] text-slate-500">Contract {money(h.old?.contract_rent)} → {money(h.new?.contract_rent)} · Tenant {money(h.old?.tenant_portion)} → {money(h.new?.tenant_portion)} · Housing {money(h.old?.housing_portion)} → {money(h.new?.housing_portion)}</div>{h.document_required ? <div className={`mt-2 text-[10px] font-black ${h.document_pending ? "text-amber-300" : "text-emerald-300"}`}>{h.document_pending ? "SUPPORTING LEASE PAPERWORK PENDING" : "SUPPORTING DOCUMENT RECORDED"}</div> : null}</div>) : <div className="text-xs text-slate-500">No rent changes recorded yet.</div>}</div>
    </Section>
  </div>;
}
