import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CalendarDays, ChevronRight, CreditCard, Loader2, Pencil, Plus, RefreshCw, Search, Send, Sparkles, UserPlus, Users, WalletCards, X } from "lucide-react";
import ModeBar from "../components/ModeBar";
import { useAuth } from "../auth/AuthContext";
import {
  acceptConnection, acceptEventInvitation, acceptMembership, cancelEvent, createCollection,
  createEvent, createEventInvitation, createEventResponse, createGroup, declineConnection,
  declineEventInvitation, declineMembership, getCollectionShares, getCollections, getConnections,
  getEventInvitations, getEventResponses, getEvents, getGroups, getMemberships, inviteMember,
  searchPeople, sendConnection, updateEvent, updateEventResponse,
} from "../api/social";

const TABS = ["Home", "People", "Groups", "Events", "Collect"];
const blankEvent = { title:"", organizer_group:"", date:"", time:"09:00", venue_name:"", address_line1:"", city:"", state:"", entryAmount:"", description:"", prizes:"", rules:"", flyer_url:"" };
const cx = (...v) => v.filter(Boolean).join(" ");
const arr = (v) => Array.isArray(v) ? v : [];
const money = (c) => (Number(c || 0) / 100).toLocaleString("en-US", { style:"currency", currency:"USD" });
const nameOf = (p) => p?.display_name || [p?.first_name,p?.last_name].filter(Boolean).join(" ") || p?.email || "SyncWorks user";
const errorText = (e) => e?.response?.data?.detail || e?.response?.data?.non_field_errors?.[0] || e?.message || "Something went wrong.";

function Btn({ children, onClick, primary, danger, disabled, className="" }) {
  return <button type="button" disabled={disabled} onClick={onClick} className={cx("min-h-11 rounded-2xl px-4 text-sm font-black disabled:opacity-50", primary ? "bg-cyan-300 text-slate-950" : danger ? "border border-rose-400/25 bg-rose-400/10 text-rose-100" : "border border-white/10 bg-white/[.04] text-slate-200", className)}>{children}</button>;
}
function Card({ title, body, children, action }) {
  return <section className="rounded-[1.6rem] border border-white/10 bg-[#07111f]/90 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-white">{title}</h2>{body && <p className="mt-1 text-sm leading-6 text-slate-400">{body}</p>}</div>{action}</div><div className="mt-4">{children}</div></section>;
}
function Sheet({ title, onClose, children }) {
  return <div className="fixed inset-0 z-[100] flex items-end bg-black/70 backdrop-blur-sm sm:items-center sm:justify-center" onMouseDown={onClose}><section onMouseDown={(e)=>e.stopPropagation()} className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[2rem] border border-white/10 bg-[#06101d] p-4 pb-[calc(1rem+env(safe-area-inset-bottom))] sm:max-w-xl sm:rounded-[2rem] sm:p-5"><div className="sticky top-0 z-10 mb-4 flex items-center justify-between bg-[#06101d]/95 pb-2"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">SyncWorks Social</div><h2 className="mt-1 text-xl font-black text-white">{title}</h2></div><button onClick={onClose} className="grid h-11 w-11 place-items-center rounded-full border border-white/10"><X className="h-5 w-5"/></button></div>{children}</section></div>;
}
function Input({ label, value, onChange, type="text", placeholder="" }) {
  return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{label}</span><input type={type} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white outline-none focus:border-cyan-400/40"/></label>;
}
function Area({ label, value, onChange }) {
  return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{label}</span><textarea rows={3} value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/40"/></label>;
}
function Status({ children, tone="slate" }) {
  const t={slate:"text-slate-300 bg-white/[.04]",cyan:"text-cyan-100 bg-cyan-400/10",green:"text-emerald-100 bg-emerald-400/10",amber:"text-amber-100 bg-amber-400/10",rose:"text-rose-100 bg-rose-400/10"};
  return <span className={cx("rounded-full border border-white/10 px-2.5 py-1 text-[10px] font-black uppercase",t[tone])}>{children}</span>;
}

export default function Connect() {
  const nav=useNavigate(); const { user }=useAuth(); const userId=Number(user?.id||0);
  const [tab,setTab]=useState("Home"), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [drawer,setDrawer]=useState(null), [error,setError]=useState(""), [notice,setNotice]=useState("");
  const [people,setPeople]=useState([]), [connections,setConnections]=useState([]), [groups,setGroups]=useState([]), [memberships,setMemberships]=useState([]), [events,setEvents]=useState([]), [invites,setInvites]=useState([]), [responses,setResponses]=useState([]), [collections,setCollections]=useState([]), [shares,setShares]=useState([]);
  const [search,setSearch]=useState(""), [inviteSearch,setInviteSearch]=useState(""), [inviteResults,setInviteResults]=useState([]), [inviteRole,setInviteRole]=useState("MEMBER"), [targetGroup,setTargetGroup]=useState("");
  const [groupForm,setGroupForm]=useState({name:"",kind:"COMMUNITY",visibility:"PRIVATE",city:"",state:""}), [eventForm,setEventForm]=useState(blankEvent), [collectionForm,setCollectionForm]=useState({title:"",group:"",event:"",total:""});

  const managed=useMemo(()=>new Set(memberships.filter(m=>m.status==="ACTIVE"&&Number(m.user)===userId&&["OWNER","DIRECTOR","MANAGER"].includes(m.role)).map(m=>Number(m.group))),[memberships,userId]);
  const active=useMemo(()=>new Set(memberships.filter(m=>m.status==="ACTIVE"&&Number(m.user)===userId).map(m=>Number(m.group))),[memberships,userId]);
  const friendIds=useMemo(()=>new Set(connections.filter(c=>c.status==="ACCEPTED").map(c=>Number(c.sender)===userId?Number(c.recipient):Number(c.sender))),[connections,userId]);
  const incoming=connections.filter(c=>c.status==="PENDING"&&Number(c.recipient)===userId);
  const membershipInvites=memberships.filter(m=>m.status==="INVITED"&&Number(m.user)===userId);
  const managerInvites=invites.filter(i=>i.status==="PENDING"&&managed.has(Number(i.target_group)));
  const myResponses=responses.filter(r=>Number(r.user)===userId);
  const pendingRsvp=myResponses.filter(r=>r.response==="PENDING");
  const actions=incoming.length+membershipInvites.length+managerInvites.length+pendingRsvp.length;

  async function load(){ setLoading(true); setError(""); const calls=await Promise.allSettled([getConnections(),getGroups(),getMemberships(),getEvents(),getEventInvitations(),getEventResponses(),getCollections(),getCollectionShares()]); const setters=[setConnections,setGroups,setMemberships,setEvents,setInvites,setResponses,setCollections,setShares]; calls.forEach((r,i)=>r.status==="fulfilled"&&setters[i](arr(r.value))); const bad=calls.find(r=>r.status==="rejected"); if(bad)setError(`Some Social data could not load: ${errorText(bad.reason)}`); setLoading(false); }
  useEffect(()=>{load();},[]);
  async function run(fn,msg,close=true){ setBusy(true);setError("");setNotice("");try{await fn();setNotice(msg);if(close)setDrawer(null);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);} }
  const group=(id)=>groups.find(g=>Number(g.id)===Number(id)); const event=(id)=>events.find(e=>Number(e.id)===Number(id));
  const roster=(id)=>memberships.filter(m=>Number(m.group)===Number(id)&&["ACTIVE","INVITED"].includes(m.status));
  const response=(eventId,groupId,uid=userId)=>responses.find(r=>Number(r.event)===Number(eventId)&&Number(r.group)===Number(groupId)&&Number(r.user)===Number(uid));
  const acceptedGroups=(ev)=>{const ids=new Set();if(ev?.organizer_group)ids.add(Number(ev.organizer_group));invites.filter(i=>Number(i.event)===Number(ev?.id)&&i.status==="ACCEPTED").forEach(i=>ids.add(Number(i.target_group)));return [...ids];};
  const canManageEvent=(ev)=>Number(ev?.created_by)===userId||(ev?.organizer_group&&managed.has(Number(ev.organizer_group)));
  const counts=(eventId,groupId)=>{const r=responses.filter(x=>Number(x.event)===Number(eventId)&&Number(x.group)===Number(groupId));return ["YES","MAYBE","NO","PENDING"].reduce((o,k)=>({...o,[k]:r.filter(x=>x.response===k).length}),{});};
  const payload=(f)=>({title:f.title.trim(),description:f.description||"",start_at:new Date(`${f.date}T${f.time||"09:00"}:00`).toISOString(),venue_name:f.venue_name||"",address_line1:f.address_line1||"",city:f.city||"",state:f.state||"",entry_amount_cents:Math.round(Number(f.entryAmount||0)*100),prizes:f.prizes||"",rules:f.rules||"",flyer_url:f.flyer_url||""});
  function editForm(ev){const d=new Date(ev.start_at),pad=n=>String(n).padStart(2,"0");return {title:ev.title||"",organizer_group:ev.organizer_group||"",date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`,venue_name:ev.venue_name||"",address_line1:ev.address_line1||"",city:ev.city||"",state:ev.state||"",entryAmount:String(Number(ev.entry_amount_cents||0)/100),description:ev.description||"",prizes:ev.prizes||"",rules:ev.rules||"",flyer_url:ev.flyer_url||""};}
  async function searchPeopleNow(q,setter){if(q.trim().length<2)return setter([]);setBusy(true);try{setter(await searchPeople(q.trim()));}catch(e){setError(errorText(e));}finally{setBusy(false);}}

  function EventFields({ form, setForm }) { return <div className="space-y-3"><Input label="Event name" value={form.title} onChange={v=>setForm(f=>({...f,title:v}))}/><div className="grid grid-cols-2 gap-3"><Input label="Date" type="date" value={form.date} onChange={v=>setForm(f=>({...f,date:v}))}/><Input label="Time" type="time" value={form.time} onChange={v=>setForm(f=>({...f,time:v}))}/></div><Input label="Venue" value={form.venue_name} onChange={v=>setForm(f=>({...f,venue_name:v}))}/><Input label="Address" value={form.address_line1} onChange={v=>setForm(f=>({...f,address_line1:v}))}/><div className="grid grid-cols-2 gap-3"><Input label="City" value={form.city} onChange={v=>setForm(f=>({...f,city:v}))}/><Input label="State" value={form.state} onChange={v=>setForm(f=>({...f,state:v}))}/></div><Input label="Entry / cost" value={form.entryAmount} onChange={v=>setForm(f=>({...f,entryAmount:v}))} placeholder="400.00"/><Area label="Description" value={form.description} onChange={v=>setForm(f=>({...f,description:v}))}/><Area label="Prizes / benefits" value={form.prizes} onChange={v=>setForm(f=>({...f,prizes:v}))}/><Area label="Rules / notes" value={form.rules} onChange={v=>setForm(f=>({...f,rules:v}))}/><Input label="Flyer image URL" value={form.flyer_url} onChange={v=>setForm(f=>({...f,flyer_url:v}))}/></div>; }

  return <div className="min-h-screen bg-[#02060c] pb-28 text-slate-100"><ModeBar title="SyncWorks Social" subtitle="People • Groups • Events • Collections"/><main className="mx-auto max-w-7xl space-y-4 px-3 py-4 sm:px-5">
    <div className="flex gap-2 overflow-x-auto pb-1">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={cx("min-h-10 shrink-0 rounded-full px-4 text-xs font-black",tab===t?"bg-white text-slate-950":"border border-white/10 text-slate-400")}>{t}</button>)}<button onClick={load} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/10"><RefreshCw className={cx("h-4 w-4",loading&&"animate-spin")}/></button></div>
    {error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</div>}{notice&&<div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-3 text-sm text-cyan-100">{notice}</div>}
    {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-cyan-300"/></div>:<>
      {tab==="Home"&&<><section className="rounded-[2rem] border border-cyan-400/20 bg-[radial-gradient(circle_at_80%_10%,rgba(34,211,238,.18),transparent_32%),#07111f] p-5 sm:p-7"><Status tone="cyan">Live Social</Status><h1 className="mt-4 text-2xl font-black sm:text-4xl">Connect people. Organize life. Keep everyone in sync.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Friends, organizations, teams, clubs, events, attendance, collections and live schedule changes in one user-level network.</p><div className="mt-5 grid grid-cols-4 gap-2">{[[friendIds.size,"Friends"],[active.size,"Groups"],[events.length,"Events"],[actions,"Actions"]].map(([v,l])=><div key={l} className="rounded-2xl bg-black/25 p-3"><div className="text-xl font-black">{v}</div><div className="text-[10px] uppercase text-slate-500">{l}</div></div>)}</div></section><Card title="Needs a response" body="Important actions stay out of buried chat threads." action={<Status tone={actions?"amber":"green"}>{actions}</Status>}><div className="space-y-2">{incoming.map(c=><button key={`c${c.id}`} onClick={()=>setDrawer({type:"connection",row:c})} className="w-full rounded-2xl border border-white/10 p-3 text-left"><b>{nameOf(c.sender_detail)}</b><div className="text-xs text-slate-500">Friend request</div></button>)}{membershipInvites.map(m=><button key={`m${m.id}`} onClick={()=>setDrawer({type:"membership",row:m})} className="w-full rounded-2xl border border-white/10 p-3 text-left"><b>{group(m.group)?.name}</b><div className="text-xs text-slate-500">Group invitation · {m.role}</div></button>)}{managerInvites.map(i=><button key={`i${i.id}`} onClick={()=>setDrawer({type:"eventInvite",row:i})} className="w-full rounded-2xl border border-white/10 p-3 text-left"><b>{event(i.event)?.title}</b><div className="text-xs text-slate-500">Manager decision · {group(i.target_group)?.name}</div></button>)}{pendingRsvp.map(r=><button key={`r${r.id}`} onClick={()=>setDrawer({type:"rsvp",row:r})} className="w-full rounded-2xl border border-cyan-400/20 bg-cyan-400/[.05] p-3 text-left"><b>{event(r.event)?.title}</b><div className="text-xs text-slate-500">Your RSVP · {group(r.group)?.name}</div></button>)}{!actions&&<div className="text-sm text-slate-500">Nothing waiting on you.</div>}</div></Card></>}
      {tab==="People"&&<><Card title="Find people" body="Connect with registered SyncWorks users."><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-4 top-4 h-4 w-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchPeopleNow(search,setPeople)} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 pl-11 pr-4" placeholder="Name or email"/></div><Btn primary onClick={()=>searchPeopleNow(search,setPeople)}>Search</Btn></div></Card><div className="grid gap-3 md:grid-cols-2">{people.map(p=>{const c=connections.find(x=>(Number(x.sender)===userId&&Number(x.recipient)===Number(p.id))||(Number(x.recipient)===userId&&Number(x.sender)===Number(p.id)));return <div key={p.id} className="rounded-2xl border border-white/10 bg-[#07111f] p-4"><b>{nameOf(p)}</b><div className="text-xs text-slate-500">{p.email}</div><div className="mt-3">{friendIds.has(Number(p.id))?<Status tone="green">Connected</Status>:c?.status==="PENDING"?<Status tone="amber">Pending</Status>:<Btn primary onClick={()=>run(()=>sendConnection(p.id),"Friend request sent.")}><UserPlus className="mr-2 inline h-4 w-4"/>Add friend</Btn>}</div></div>})}</div></>}
      {tab==="Groups"&&<Card title="Groups" body="Organization → division/chapter → team/group → members." action={<Btn primary onClick={()=>setDrawer({type:"createGroup"})}><Plus className="mr-1 inline h-4 w-4"/>Create</Btn>}><div className="grid gap-3 md:grid-cols-3">{groups.map(g=><button key={g.id} onClick={()=>setDrawer({type:"group",row:g})} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left"><div className="flex justify-between gap-2"><b>{g.name}</b><Status>{g.kind}</Status></div><div className="mt-2 text-xs text-slate-500">{g.member_count||0} members</div><div className="mt-4 flex justify-between text-xs font-black">Open roster <ChevronRight className="h-4 w-4"/></div></button>)}</div></Card>}
      {tab==="Events"&&<Card title="Events" body="Accepted events sync to members’ SyncWorks calendars; organizer edits update the same entry." action={<Btn primary onClick={()=>{setEventForm(blankEvent);setDrawer({type:"createEvent"});}}><Plus className="mr-1 inline h-4 w-4"/>Create</Btn>}><div className="space-y-3">{events.map(ev=><button key={ev.id} onClick={()=>setDrawer({type:"event",row:ev})} className="w-full rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left"><div className="flex justify-between gap-3"><div><b>{ev.title}</b><div className="mt-1 text-xs text-slate-400">{new Date(ev.start_at).toLocaleString()} · {ev.venue_name||"Location TBD"}</div><div className="text-xs text-slate-500">{money(ev.entry_amount_cents)} · version {ev.version}</div></div><Status tone={ev.status==="CANCELLED"?"rose":"cyan"}>{ev.status}</Status></div></button>)}</div></Card>}
      {tab==="Collect"&&<><Card title="Collections" body="Track who owes what and attach collections to an event." action={<Btn primary onClick={()=>setDrawer({type:"createCollection"})}><Plus className="mr-1 inline h-4 w-4"/>Create</Btn>}><div className="space-y-3">{collections.map(c=><button key={c.id} onClick={()=>setDrawer({type:"collection",row:c})} className="w-full rounded-2xl border border-white/10 p-4 text-left"><div className="flex justify-between"><b>{c.title}</b><Status tone={c.status==="FUNDED"?"green":"amber"}>{c.status}</Status></div><div className="mt-2 text-xs text-slate-500">{group(c.group)?.name} · {money(c.collected_amount_cents)} / {money(c.total_amount_cents)}</div></button>)}</div></Card><Card title="Payment rails" body="Stripe, Venmo and Cash App remain staged until the payment-execution build."><div className="grid grid-cols-3 gap-2">{[[CreditCard,"Stripe"],[WalletCards,"Venmo"],[WalletCards,"Cash App"]].map(([I,n])=><div key={n} className="rounded-2xl border border-white/10 p-3"><I className="h-5 w-5 text-cyan-300"/><b className="mt-2 block text-sm">{n}</b></div>)}</div></Card></>}
    </>}
    <button onClick={()=>nav("/calendar")} className="flex min-h-12 w-full items-center justify-between rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] px-4 text-sm font-black text-emerald-100"><span><CalendarDays className="mr-2 inline h-4 w-4"/>Open SyncWorks Calendar</span><ChevronRight className="h-4 w-4"/></button>
  </main>

  {drawer?.type==="connection"&&<Sheet title="Friend request" onClose={()=>setDrawer(null)}><div className="grid grid-cols-2 gap-2"><Btn primary onClick={()=>run(()=>acceptConnection(drawer.row.id),"Friend request accepted.")}>Accept</Btn><Btn danger onClick={()=>run(()=>declineConnection(drawer.row.id),"Friend request declined.")}>Decline</Btn></div></Sheet>}
  {drawer?.type==="membership"&&<Sheet title="Group invitation" onClose={()=>setDrawer(null)}><p className="mb-4 text-sm text-slate-400">Join {group(drawer.row.group)?.name} as {drawer.row.role}?</p><div className="grid grid-cols-2 gap-2"><Btn primary onClick={()=>run(()=>acceptMembership(drawer.row.id),"Group joined.")}>Join</Btn><Btn danger onClick={()=>run(()=>declineMembership(drawer.row.id),"Invitation declined.")}>Decline</Btn></div></Sheet>}
  {drawer?.type==="createGroup"&&<Sheet title="Create group" onClose={()=>setDrawer(null)}><div className="space-y-3"><Input label="Name" value={groupForm.name} onChange={v=>setGroupForm(f=>({...f,name:v}))}/><select value={groupForm.kind} onChange={e=>setGroupForm(f=>({...f,kind:e.target.value}))} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="ORGANIZATION">Organization</option><option value="DIVISION">Division / chapter</option><option value="TEAM">Team</option><option value="CLUB">Club</option><option value="COMMUNITY">Community</option><option value="OTHER">Other</option></select><div className="grid grid-cols-2 gap-2"><Input label="City" value={groupForm.city} onChange={v=>setGroupForm(f=>({...f,city:v}))}/><Input label="State" value={groupForm.state} onChange={v=>setGroupForm(f=>({...f,state:v}))}/></div><Btn primary className="w-full" disabled={!groupForm.name.trim()} onClick={()=>run(()=>createGroup(groupForm),"Group created.")}>Create group</Btn></div></Sheet>}
  {drawer?.type==="group"&&<Sheet title={drawer.row.name} onClose={()=>setDrawer(null)}><div className="space-y-2">{roster(drawer.row.id).map(m=><div key={m.id} className="flex justify-between rounded-2xl border border-white/10 p-3"><div><b>{nameOf(m.user_detail)}</b><div className="text-xs text-slate-500">{m.role}</div></div><Status tone={m.status==="ACTIVE"?"green":"amber"}>{m.status}</Status></div>)}</div>{managed.has(Number(drawer.row.id))&&<Btn primary className="mt-4 w-full" onClick={()=>{setInviteSearch("");setInviteResults([]);setDrawer({type:"inviteMember",row:drawer.row});}}><UserPlus className="mr-2 inline h-4 w-4"/>Invite member</Btn>}</Sheet>}
  {drawer?.type==="inviteMember"&&<Sheet title={`Invite to ${drawer.row.name}`} onClose={()=>setDrawer(null)}><div className="space-y-3"><div className="flex gap-2"><input value={inviteSearch} onChange={e=>setInviteSearch(e.target.value)} className="h-12 flex-1 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Name or email"/><Btn primary onClick={()=>searchPeopleNow(inviteSearch,setInviteResults)}>Search</Btn></div><select value={inviteRole} onChange={e=>setInviteRole(e.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="MEMBER">Member</option><option value="MANAGER">Manager / Coach</option><option value="DIRECTOR">Director</option></select>{inviteResults.map(p=><div key={p.id} className="flex items-center justify-between rounded-2xl border border-white/10 p-3"><div><b>{nameOf(p)}</b><div className="text-xs text-slate-500">{p.email}</div></div><Btn primary onClick={()=>run(()=>inviteMember({group:Number(drawer.row.id),user:Number(p.id),role:inviteRole}),"Member invited.",false)}>Invite</Btn></div>)}</div></Sheet>}

  {drawer?.type==="createEvent"&&<Sheet title="Create event" onClose={()=>setDrawer(null)}><div className="space-y-3"><select value={eventForm.organizer_group} onChange={e=>setEventForm(f=>({...f,organizer_group:e.target.value}))} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="">Personal event</option>{groups.filter(g=>managed.has(Number(g.id))).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><EventFields form={eventForm} setForm={setEventForm}/><Btn primary className="w-full" disabled={!eventForm.title.trim()||!eventForm.date} onClick={()=>{const p={...payload(eventForm),status:"PUBLISHED"};if(eventForm.organizer_group)p.organizer_group=Number(eventForm.organizer_group);return run(()=>createEvent(p),"Event created and added to SyncWorks Calendar.");}}>Create event</Btn></div></Sheet>}
  {drawer?.type==="event"&&<Sheet title={drawer.row.title} onClose={()=>setDrawer(null)}><div className="space-y-4"><div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.05] p-4"><div className="flex justify-between gap-3"><div><b>{new Date(drawer.row.start_at).toLocaleString()}</b><div className="mt-1 text-xs text-slate-400">{drawer.row.venue_name||"Venue TBD"}</div><div className="text-xs text-slate-500">{[drawer.row.address_line1,drawer.row.city,drawer.row.state].filter(Boolean).join(", ")}</div></div><Status tone={drawer.row.status==="CANCELLED"?"rose":"cyan"}>v{drawer.row.version}</Status></div><div className="mt-3 text-sm">{money(drawer.row.entry_amount_cents)}</div>{drawer.row.description&&<p className="mt-2 text-sm text-slate-300">{drawer.row.description}</p>}{drawer.row.prizes&&<p className="mt-2 text-xs text-slate-400"><b>Prizes:</b> {drawer.row.prizes}</p>}{drawer.row.rules&&<p className="mt-2 text-xs text-slate-400"><b>Rules:</b> {drawer.row.rules}</p>}</div>{canManageEvent(drawer.row)&&drawer.row.status!=="CANCELLED"&&<div className="grid grid-cols-2 gap-2"><Btn primary onClick={()=>{setEventForm(editForm(drawer.row));setDrawer({type:"editEvent",row:drawer.row});}}><Pencil className="mr-1 inline h-4 w-4"/>Edit</Btn><Btn onClick={()=>{setTargetGroup("");setDrawer({type:"inviteGroup",row:drawer.row});}}><Send className="mr-1 inline h-4 w-4"/>Invite group</Btn></div>}{acceptedGroups(drawer.row).map(gid=>{const c=counts(drawer.row.id,gid),mine=active.has(gid)?response(drawer.row.id,gid):null;return <div key={gid} className="rounded-2xl border border-white/10 p-4"><div className="flex justify-between"><b>{group(gid)?.name}</b><Status tone="green">Accepted</Status></div><div className="mt-3 grid grid-cols-4 gap-1 text-center text-xs"><div>Yes<br/><b>{c.YES}</b></div><div>Maybe<br/><b>{c.MAYBE}</b></div><div>No<br/><b>{c.NO}</b></div><div>Pending<br/><b>{c.PENDING}</b></div></div>{mine&&<Btn primary className="mt-3 w-full" onClick={()=>setDrawer({type:"rsvp",row:mine})}>My RSVP: {mine.response}</Btn>}{managed.has(gid)&&<Btn className="mt-2 w-full" onClick={()=>setDrawer({type:"attendance",event:drawer.row,group:group(gid)})}>View attendance</Btn>}</div>})}<div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-3 text-xs text-emerald-100">Calendar sync: accepted members receive one linked SyncWorks Calendar event. Organizer edits update that event; cancellation marks it cancelled.</div><Btn className="w-full" onClick={()=>nav("/calendar")}><CalendarDays className="mr-2 inline h-4 w-4"/>Open calendar</Btn>{canManageEvent(drawer.row)&&drawer.row.status!=="CANCELLED"&&<Btn danger className="w-full" onClick={()=>run(()=>cancelEvent(drawer.row.id),"Event cancelled; linked calendars will update.")}>Cancel event</Btn>}</div></Sheet>}
  {drawer?.type==="editEvent"&&<Sheet title="Edit event" onClose={()=>setDrawer(null)}><div className="space-y-3"><div className="rounded-2xl border border-amber-400/20 bg-amber-400/[.05] p-3 text-xs text-amber-100">Saving increments the Social event version and updates linked calendars.</div><EventFields form={eventForm} setForm={setEventForm}/><Btn primary className="w-full" disabled={!eventForm.title.trim()||!eventForm.date} onClick={()=>run(()=>updateEvent(drawer.row.id,payload(eventForm)),"Event updated and calendars synchronized.")}>Save changes</Btn></div></Sheet>}
  {drawer?.type==="inviteGroup"&&<Sheet title="Invite group" onClose={()=>setDrawer(null)}><div className="space-y-3"><p className="text-sm text-slate-400">The group’s owner/director/manager accepts or declines. Acceptance creates member RSVP actions and calendar entries.</p><select value={targetGroup} onChange={e=>setTargetGroup(e.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="">Choose group / team</option>{groups.filter(g=>Number(g.id)!==Number(drawer.row.organizer_group)&&!invites.some(i=>Number(i.event)===Number(drawer.row.id)&&Number(i.target_group)===Number(g.id))).map(g=><option key={g.id} value={g.id}>{g.name} · {g.kind}</option>)}</select><Btn primary className="w-full" disabled={!targetGroup} onClick={()=>run(()=>createEventInvitation({event:Number(drawer.row.id),target_group:Number(targetGroup)}),"Group invitation sent.")}>Send invitation</Btn></div></Sheet>}
  {drawer?.type==="eventInvite"&&<Sheet title="Event invitation" onClose={()=>setDrawer(null)}><p className="mb-4"><b>{event(drawer.row.event)?.title}</b><br/><span className="text-sm text-slate-500">For {group(drawer.row.target_group)?.name}</span></p><div className="grid grid-cols-2 gap-2"><Btn primary onClick={()=>run(()=>acceptEventInvitation(drawer.row.id),"Group accepted; member RSVPs and calendars will be created.")}>Accept</Btn><Btn danger onClick={()=>run(()=>declineEventInvitation(drawer.row.id),"Event declined.")}>Decline</Btn></div></Sheet>}
  {drawer?.type==="rsvp"&&<Sheet title="Your availability" onClose={()=>setDrawer(null)}><p className="mb-4 text-sm text-slate-400">{event(drawer.row.event)?.title} · {group(drawer.row.group)?.name}</p><div className="space-y-2">{["YES","MAYBE","NO"].map(v=><Btn key={v} className="w-full" primary={v==="YES"} danger={v==="NO"} onClick={()=>run(()=>updateEventResponse(drawer.row.id,v),`RSVP saved: ${v}.`)}>{v==="YES"?"Yes — I can attend":v==="MAYBE"?"Maybe":"No — unavailable"}</Btn>)}</div></Sheet>}
  {drawer?.type==="attendance"&&<Sheet title={`${drawer.group?.name} attendance`} onClose={()=>setDrawer(null)}><div className="space-y-2">{roster(drawer.group.id).filter(m=>m.status==="ACTIVE").map(m=>{const r=response(drawer.event.id,drawer.group.id,m.user);return <div key={m.id} className="flex justify-between rounded-2xl border border-white/10 p-3"><div><b>{nameOf(m.user_detail)}</b><div className="text-xs text-slate-500">{m.role}</div></div><Status tone={r?.response==="YES"?"green":r?.response==="NO"?"rose":r?.response==="MAYBE"?"amber":"slate"}>{r?.response||"PENDING"}</Status></div>})}</div></Sheet>}

  {drawer?.type==="createCollection"&&<Sheet title="Create collection" onClose={()=>setDrawer(null)}><div className="space-y-3"><Input label="Name" value={collectionForm.title} onChange={v=>setCollectionForm(f=>({...f,title:v}))}/><select value={collectionForm.group} onChange={e=>setCollectionForm(f=>({...f,group:e.target.value}))} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="">Managed group</option>{groups.filter(g=>managed.has(Number(g.id))).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select value={collectionForm.event} onChange={e=>setCollectionForm(f=>({...f,event:e.target.value}))} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4"><option value="">Optional event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><Input label="Total" value={collectionForm.total} onChange={v=>setCollectionForm(f=>({...f,total:v}))}/><Btn primary className="w-full" disabled={!collectionForm.title||!collectionForm.group} onClick={()=>{const p={title:collectionForm.title,group:Number(collectionForm.group),total_amount_cents:Math.round(Number(collectionForm.total||0)*100),split_method:"EQUAL",status:"OPEN"};if(collectionForm.event)p.event=Number(collectionForm.event);return run(()=>createCollection(p),"Collection created.");}}>Create</Btn></div></Sheet>}
  {drawer?.type==="collection"&&<Sheet title={drawer.row.title} onClose={()=>setDrawer(null)}><div className="mb-3 text-sm text-slate-400">{money(drawer.row.collected_amount_cents)} collected of {money(drawer.row.total_amount_cents)}</div><div className="space-y-2">{arr(drawer.row.shares).map(s=><div key={s.id} className="flex justify-between rounded-2xl border border-white/10 p-3"><div><b>{nameOf(s.user_detail)}</b><div className="text-xs text-slate-500">{money(s.amount_due_cents)}</div></div><Status tone={s.status==="PAID"?"green":"amber"}>{s.status}</Status></div>)}</div></Sheet>}
  </div>;
}
