import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import GodModeLiveUsers from "./GodModeLiveUsers";
import GodModeGrowthOperations from "./GodModeGrowthOperations";
import GodModeBuildBacklog from "../components/platform/GodModeBuildBacklog";

const tabs = ["command", "users", "approvals", "support", "billing", "backlog", "growth", "automations"];
const projects = [
  ["Live user intelligence", "TESTING", 98, "Master Operations Agent", "Verify production roles, subscription signals and value lineage"],
  ["Growth + revenue intelligence", "TESTING", 92, "Master Operations Agent", "Verify day/week/month views, cohorts and source attribution"],
  ["Support ticket intelligence", "READY TO BUILD", 35, "Support Agent", "Connect internal messages and support tickets"],
  ["Billing enforcement foundation", "AUDIT NEEDED", 20, "Billing Watch Agent", "Verify grace period and webhook restoration"],
  ["Growth OS connection center", "IN PROGRESS", 60, "Growth Agent", "Meta live; build LinkedIn, TikTok, YouTube and X connectors"],
  ["Automation health monitor", "IN PROGRESS", 60, "Automation Agent", "Add failure alerts and heartbeat monitoring"],
];
const approvals = [
  ["Audit login and session stability", "Inspect login, API availability, CORS, saved-token recovery, and mobile inactivity behavior."],
  ["Build billing restriction foundation", "Add billing states, 30-day grace rules, notices, restricted access, and webhook-confirmed restoration."],
];
const activities = ["Founder-only God Mode access enforced", "Growth and revenue intelligence upgraded", "Build Backlog moved to SyncWorks database", "Growth OS connection center unified"];

function Card({ children, className = "" }) { return <div className={`rounded-[24px] border border-cyan-400/15 bg-[#071128]/90 shadow-[0_20px_60px_rgba(0,0,0,.28)] ${className}`}>{children}</div>; }
function Stat({ icon, label, value, note, tone = "cyan" }) {
  const tones = { cyan: "from-cyan-500/20 to-blue-700/10 border-cyan-400/25", purple: "from-violet-500/20 to-fuchsia-700/10 border-violet-400/25", amber: "from-amber-500/20 to-orange-700/10 border-amber-400/25", pink: "from-pink-500/20 to-fuchsia-700/10 border-pink-400/25" };
  return <div className={`rounded-[22px] border bg-gradient-to-br p-4 ${tones[tone]}`}><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full border border-white/10 bg-slate-950/60 text-xl">{icon}</div><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{label}</div><div className="mt-1 text-2xl font-black text-white">{value}</div><div className="mt-1 text-xs text-slate-500">{note}</div></div></div><div className="mt-4 h-px bg-gradient-to-r from-transparent via-cyan-400/40 to-transparent" /></div>;
}
function tabLabel(id) { if (id === "backlog") return "Build Backlog"; if (id === "growth") return "Growth OS"; return id; }

export default function GodModeCompanyOperations() {
  const params = new URLSearchParams(window.location.search);
  const [tab, setTab] = useState(() => params.has("social_connected") || params.has("social_error") ? "growth" : "command");
  const [liveMetrics, setLiveMetrics] = useState({ real: 0, beta: 0, test: 0, total: 0 });
  const [decisions, setDecisions] = useState({});
  const metrics = useMemo(() => ({ ...liveMetrics, pending: approvals.filter(([title]) => !decisions[title]).length }), [liveMetrics, decisions]);

  return <div className="min-h-screen bg-[#020617] text-slate-200">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_10%_45%,rgba(0,102,255,.18),transparent_30%),radial-gradient(circle_at_92%_80%,rgba(168,40,255,.18),transparent_32%)]" />
    <main className="relative mx-auto max-w-[1900px] p-3 pb-28 sm:p-5 lg:p-7">
      <Card className="mb-4 overflow-hidden"><div className="bg-[linear-gradient(110deg,rgba(0,180,255,.08),transparent_44%,rgba(168,40,255,.12))] p-5 sm:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><div className="inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.22em] text-cyan-200">SyncWorks Operations Board</div><h1 className="mt-4 text-3xl font-black tracking-[.08em] text-white sm:text-5xl">SYNCWORKS <span className="bg-gradient-to-r from-cyan-300 via-blue-500 to-fuchsia-400 bg-clip-text text-transparent">GOD MODE</span></h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Private founder command center for live users, acquisition, verified value, billing, growth, approvals, builds, automations and launch readiness.</p></div><div className="flex flex-wrap gap-2"><Link to="/platform?tab=developer_agent" className="rounded-xl border border-cyan-400/40 bg-blue-600/20 px-5 py-3 text-sm font-black text-cyan-100">Developer Agent</Link><button type="button" onClick={() => setTab("growth")} className="rounded-xl bg-gradient-to-r from-blue-600 to-fuchsia-600 px-5 py-3 text-sm font-black text-white">Social Media</button></div></div><div className="mt-5 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-slate-950/40 p-2">{tabs.map((id) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-black capitalize transition ${tab === id ? "bg-cyan-400/15 text-cyan-200 shadow-[inset_0_-2px_0_#22d3ee]" : "text-slate-400 hover:text-white"}`}>{tabLabel(id)}</button>)}</div></div></Card>

      <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6"><Stat icon="$" label="Verified Revenue" value="$0" note="Top-card aggregation is the next billing feed" /><Stat icon="◎" label="Registered Users" value={metrics.total} note="Loaded from production" tone="purple" /><Stat icon="●" label="Real Users" value={metrics.real} note="God Mode classified" /><Stat icon="⚗" label="Beta Testers" value={metrics.beta} note="Primary or tagged" tone="purple" /><Stat icon="✓" label="Test Accounts" value={metrics.test} note="Excluded from adoption" tone="purple" /><Stat icon="!" label="Needs Approval" value={metrics.pending} note="Build plans waiting" tone="amber" /></div>

      {tab === "users" && <GodModeLiveUsers onMetrics={setLiveMetrics} />}
      {tab === "backlog" && <GodModeBuildBacklog />}
      {tab === "growth" && <GodModeGrowthOperations />}

      {tab === "command" && <div className="grid gap-4 xl:grid-cols-12"><Card className="xl:col-span-8"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><div className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Build Pipeline / Projects</div><div className="text-xs text-slate-500">Key initiatives powering SyncWorks</div></div><button onClick={() => setTab("approvals")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">View approvals →</button></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(([title, stage, progress, owner, next]) => <div key={title} className="rounded-2xl border border-cyan-400/15 bg-slate-950/45 p-4 hover:border-cyan-400/45"><div className="font-black text-white">{title}</div><div className="mt-3 flex items-center justify-between text-xs"><span className="rounded-full border border-violet-400/30 bg-violet-400/10 px-2 py-1 font-bold text-violet-200">{stage}</span><span className="font-black text-white">{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-gradient-to-r from-cyan-400 via-blue-500 to-fuchsia-500" style={{ width: `${progress}%` }} /></div><div className="mt-3 text-[11px] text-slate-500">{owner}</div><div className="mt-2 text-xs text-slate-400"><b className="text-white">Next:</b> {next}</div></div>)}</div></Card><div className="space-y-4 xl:col-span-4"><Card><div className="border-b border-white/10 p-4 text-xs font-black uppercase tracking-[.18em] text-white">Recent Activity</div><div className="space-y-3 p-4">{activities.map((item, index) => <div key={item} className="flex gap-3"><div className={`mt-1 h-3 w-3 rounded-full ${index % 2 ? "bg-violet-400" : "bg-cyan-400"}`} /><div><div className="text-sm text-white">{item}</div><div className="text-[10px] text-slate-600">Operational record</div></div></div>)}</div></Card><div className="grid gap-3 sm:grid-cols-2"><Card className="p-5"><div className="text-xs font-black uppercase text-cyan-300">Launch Readiness</div><div className="mt-3 text-4xl font-black text-white">72%</div><div className="mt-1 text-xs text-slate-500">Foundation progressing</div></Card><Card className="p-5"><div className="text-xs font-black uppercase text-violet-300">Automation Status</div><div className="mt-3 text-4xl font-black text-white">7</div><div className="mt-1 text-xs text-slate-500">Controlled agents</div></Card></div></div></div>}

      {tab === "approvals" && <div className="grid gap-4 lg:grid-cols-2">{approvals.map(([title, proposal]) => <Card key={title} className="p-5"><div className="flex justify-between gap-3"><h2 className="text-xl font-black text-white">{title}</h2><span className="rounded-full border border-fuchsia-400/30 bg-fuchsia-400/10 px-2 py-1 text-[10px] font-black text-fuchsia-200">{decisions[title] || "PENDING"}</span></div><div className="mt-4 text-sm leading-6 text-slate-400"><b className="text-white">What the bot proposes:</b><br />{proposal}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setDecisions((s) => ({ ...s, [title]: "APPROVED" }))} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">Approve</button><button onClick={() => setDecisions((s) => ({ ...s, [title]: "DENIED" }))} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white">Deny</button><button onClick={() => setDecisions((s) => ({ ...s, [title]: "CHANGES REQUESTED" }))} className="rounded-xl border border-amber-400/30 px-4 py-2 text-sm font-black text-amber-200">Request changes</button></div></Card>)}</div>}
      {tab === "support" && <Card className="p-6"><h2 className="text-2xl font-black text-white">Support Operations</h2><p className="mt-2 text-slate-400">Internal messages, manual support tickets, bot-suggested issues and escalations will feed this queue from the backend.</p></Card>}
      {tab === "billing" && <Card className="p-6"><h2 className="text-2xl font-black text-white">Billing Operations</h2><p className="mt-2 text-slate-400">Verified revenue, billing warnings, grace periods, restrictions, payment methods and payment-confirmed restoration belong here. This tab is the next operating-console hardening target.</p></Card>}
      {tab === "automations" && <Card className="p-6"><h2 className="text-2xl font-black text-white">Automation Control Center</h2><p className="mt-2 text-slate-400">Build, deployment, billing and customer-facing actions remain approval required. Audits and recommendations can operate in assist-only mode.</p></Card>}
    </main>
  </div>;
}
