import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronRight, ListTodo, Loader2, Plus, Search, ShoppingCart, Target, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import ModeBar from "../components/ModeBar";
import { useAuth } from "../auth/AuthContext";
import { createGroup, inviteMember, searchPeople } from "../api/social";
import { createHousehold, createHouseholdGoal, createHouseholdMeal, createHouseholdTask, createShoppingItem, getHouseholdGoals, getHouseholdMeals, getHouseholdSettings, getHouseholdTasks, getHouseholds, getShoppingItems, syncHouseholdMembers, updateHouseholdGoal, updateHouseholdSettings, updateHouseholdTask, updateShoppingItem } from "../api/household";

const AMAZON_TAG = "syncworksapp-20";
const tabs = ["Today", "Tasks", "Shopping", "Goals", "Meals", "Sharing"];
const cx = (...v) => v.filter(Boolean).join(" ");
const todayYmd = () => new Date().toISOString().slice(0,10);
const err = (e) => e?.response?.data?.detail || e?.response?.data?.non_field_errors?.[0] || e?.message || "Something went wrong.";
const amazonUrl = (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}&tag=${AMAZON_TAG}`;
const walmartUrl = (q) => `https://www.walmart.com/search?q=${encodeURIComponent(q)}`;

function Card({title,subtitle,children,action}){return <section className="rounded-[1.6rem] border border-white/10 bg-[#07111f] p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-white">{title}</h2>{subtitle?<p className="mt-1 text-sm text-slate-400">{subtitle}</p>:null}</div>{action}</div><div className="mt-4">{children}</div></section>}
function Input({label,value,onChange,type="text",placeholder=""}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white outline-none focus:border-cyan-400/40"/></label>}
function Btn({children,onClick,primary=false,disabled=false,className=""}){return <button type="button" disabled={disabled} onClick={onClick} className={cx("min-h-11 rounded-2xl px-4 text-sm font-black disabled:opacity-40",primary?"bg-cyan-300 text-slate-950":"border border-white/10 bg-white/[.04] text-slate-200",className)}>{children}</button>}

export default function Household(){
  const nav=useNavigate(); const {user}=useAuth(); const userId=Number(user?.id||0);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("Today");
  const [households,setHouseholds]=useState([]),[settings,setSettings]=useState([]),[tasks,setTasks]=useState([]),[shopping,setShopping]=useState([]),[goals,setGoals]=useState([]),[meals,setMeals]=useState([]);
  const [setup,setSetup]=useState({name:"",address_line1:"",address_line2:"",city:"",state:"",postal_code:"",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Chicago"});
  const [memberSearch,setMemberSearch]=useState(""),[memberResults,setMemberResults]=useState([]),[selectedMembers,setSelectedMembers]=useState([]);
  const [taskForm,setTaskForm]=useState({title:"",due_at:"",estimated_minutes:"15",requires_phone:false,requires_computer:false,requires_focus:false,can_multitask:true});
  const [shopName,setShopName]=useState(""),[goalForm,setGoalForm]=useState({title:"",cadence:"WEEKLY",target_value:"1",unit:""}),[mealForm,setMealForm]=useState({date:todayYmd(),meal_type:"DINNER",title:""});
  const household=households[0]||null;
  const mySettings=settings.find(s=>Number(s.user)===userId&&Number(s.household)===Number(household?.id));

  async function load(){setLoading(true);setError("");try{const [h,s,t,sh,g,m]=await Promise.all([getHouseholds(),getHouseholdSettings(),getHouseholdTasks(),getShoppingItems(),getHouseholdGoals(),getHouseholdMeals()]);setHouseholds(h);setSettings(s);setTasks(t);setShopping(sh);setGoals(g);setMeals(m);}catch(e){setError(err(e));}finally{setLoading(false)}}
  useEffect(()=>{load();},[]);
  async function run(fn,msg){setBusy(true);setError("");setNotice("");try{await fn();setNotice(msg);await load();}catch(e){setError(err(e));}finally{setBusy(false)}}

  async function findMembers(){if(memberSearch.trim().length<2)return;setBusy(true);try{setMemberResults(await searchPeople(memberSearch.trim()));}catch(e){setError(err(e));}finally{setBusy(false)}}
  function toggleSelected(person){setSelectedMembers(cur=>cur.some(p=>p.id===person.id)?cur.filter(p=>p.id!==person.id):[...cur,person]);}
  async function createFamily(){setBusy(true);setError("");try{const group=await createGroup({name:setup.name.trim(),kind:"HOUSEHOLD",visibility:"INVITE_ONLY",city:setup.city,state:setup.state});const h=await createHousehold({group:group.id,address_line1:setup.address_line1,address_line2:setup.address_line2,city:setup.city,state:setup.state,postal_code:setup.postal_code,country:"US",timezone:setup.timezone});for(const p of selectedMembers){await inviteMember({group:group.id,user:p.id,role:"MEMBER"});}await syncHouseholdMembers(h.id);setNotice("Family workspace created. Invited members must accept before Household sharing becomes active.");await load();}catch(e){setError(err(e));}finally{setBusy(false)}}

  const openTasks=tasks.filter(t=>Number(t.household)===Number(household?.id)&&t.status!=="DONE");
  const unchecked=shopping.filter(i=>Number(i.household)===Number(household?.id)&&!i.is_checked);
  const activeGoals=goals.filter(g=>Number(g.household)===Number(household?.id)&&!g.is_complete);
  const todaysMeals=meals.filter(m=>Number(m.household)===Number(household?.id)&&m.date===todayYmd());

  if(loading)return <div className="min-h-screen bg-[#02060c] text-white"><ModeBar title="Family" subtitle="Household coordination"/><div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-cyan-300"/></div></div>;

  if(!household)return <div className="min-h-screen bg-[#02060c] pb-24 text-white"><ModeBar title="Family" subtitle="Create time by coordinating the household"/><main className="mx-auto max-w-3xl space-y-4 px-3 py-5 sm:px-5"><Card title="Create your Family workspace" subtitle="This is different from a normal Social group. Joining does not expose anyone’s finances. Each member controls what they share."><div className="space-y-3"><Input label="Family / household name" value={setup.name} onChange={v=>setSetup(x=>({...x,name:v}))} placeholder="Lord Family"/><Input label="Street address" value={setup.address_line1} onChange={v=>setSetup(x=>({...x,address_line1:v}))}/><Input label="Address line 2" value={setup.address_line2} onChange={v=>setSetup(x=>({...x,address_line2:v}))}/><div className="grid grid-cols-3 gap-2"><Input label="City" value={setup.city} onChange={v=>setSetup(x=>({...x,city:v}))}/><Input label="State" value={setup.state} onChange={v=>setSetup(x=>({...x,state:v}))}/><Input label="ZIP" value={setup.postal_code} onChange={v=>setSetup(x=>({...x,postal_code:v}))}/></div></div></Card><Card title="Invite family now" subtitle="Search registered SyncWorks users. They must accept the invitation before they become active Household members."><div className="flex gap-2"><input value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&findMembers()} className="h-12 flex-1 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Name or email"/><Btn primary onClick={findMembers}><Search className="h-4 w-4"/></Btn></div><div className="mt-3 space-y-2">{memberResults.map(p=><button key={p.id} onClick={()=>toggleSelected(p)} className={cx("flex w-full items-center justify-between rounded-2xl border p-3 text-left",selectedMembers.some(x=>x.id===p.id)?"border-cyan-300/40 bg-cyan-300/10":"border-white/10")}><span><b>{p.display_name||p.email}</b><span className="block text-xs text-slate-500">{p.email}</span></span>{selectedMembers.some(x=>x.id===p.id)?<Check className="h-5 w-5 text-cyan-300"/>:<Plus className="h-5 w-5"/>}</button>)}</div><Btn primary className="mt-4 w-full" disabled={busy||!setup.name.trim()} onClick={createFamily}>Create Family workspace</Btn></Card>{error?<div className="rounded-2xl bg-rose-400/10 p-3 text-sm text-rose-100">{error}</div>:null}</main></div>;

  return <div className="min-h-screen bg-[#02060c] pb-28 text-white"><ModeBar title={household.group_name||"Family"} subtitle="Household operations • powered by SYNC"/><main className="mx-auto max-w-7xl space-y-4 px-3 py-4 sm:px-5">{error?<div className="rounded-2xl bg-rose-400/10 p-3 text-sm text-rose-100">{error}</div>:null}{notice?<div className="rounded-2xl bg-cyan-400/10 p-3 text-sm text-cyan-100">{notice}</div>:null}<div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={cx("min-h-10 shrink-0 rounded-full px-4 text-xs font-black",tab===t?"bg-white text-slate-950":"border border-white/10 text-slate-400")}>{t}</button>)}</div>

  {tab==="Today"?<><section className="rounded-[2rem] border border-cyan-400/20 bg-[radial-gradient(circle_at_80%_10%,rgba(34,211,238,.17),transparent_34%),#07111f] p-5 sm:p-7"><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">SYNC Household Briefing</div><h1 className="mt-2 text-2xl font-black sm:text-4xl">What needs to get done?</h1><p className="mt-2 text-sm leading-6 text-slate-300">{openTasks.length} open tasks · {unchecked.length} shopping items · {activeGoals.length} active goals · {todaysMeals.length} meals planned today.</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[[ListTodo,openTasks.length,"Tasks"],[ShoppingCart,unchecked.length,"Shopping"],[Target,activeGoals.length,"Goals"],[Users,settings.length,"Members"]].map(([I,v,l])=><button key={l} onClick={()=>setTab(l==="Members"?"Sharing":l)} className="rounded-2xl border border-white/10 bg-black/20 p-3 text-left"><I className="h-4 w-4 text-cyan-300"/><div className="mt-2 text-xl font-black">{v}</div><div className="text-[10px] uppercase text-slate-500">{l}</div></button>)}</div></section><Card title="Family Calendar" subtitle="Household calendar coordination stays separate from private Finance sharing." action={<Btn onClick={()=>nav("/calendar")}>Open <ChevronRight className="ml-1 inline h-4 w-4"/></Btn>}><p className="text-sm text-slate-400">Connect multiple Google/Outlook calendars in SyncWorks Calendar and choose what the Household can coordinate.</p></Card></>:null}

  {tab==="Tasks"?<Card title="Shared Tasks" subtitle="SYNC can later use time, location and device requirements to recommend what can be accomplished now."><div className="grid gap-2 sm:grid-cols-[1fr_140px_auto]"><input value={taskForm.title} onChange={e=>setTaskForm(x=>({...x,title:e.target.value}))} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Call insurance company"/><input value={taskForm.estimated_minutes} onChange={e=>setTaskForm(x=>({...x,estimated_minutes:e.target.value}))} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Minutes"/><Btn primary disabled={!taskForm.title.trim()} onClick={()=>run(()=>createHouseholdTask({household:household.id,title:taskForm.title,estimated_minutes:Number(taskForm.estimated_minutes||15),requires_phone:taskForm.requires_phone,requires_computer:taskForm.requires_computer,requires_focus:taskForm.requires_focus,can_multitask:taskForm.can_multitask}),"Task added.")}>Add</Btn></div><div className="mt-3 flex flex-wrap gap-2 text-xs">{[["requires_phone","Phone"],["requires_computer","Computer"],["requires_focus","Focus"],["can_multitask","Can multitask"]].map(([k,l])=><label key={k} className="rounded-full border border-white/10 px-3 py-2"><input type="checkbox" checked={!!taskForm[k]} onChange={e=>setTaskForm(x=>({...x,[k]:e.target.checked}))} className="mr-2"/>{l}</label>)}</div><div className="mt-4 space-y-2">{tasks.filter(t=>Number(t.household)===Number(household.id)).map(t=><button key={t.id} onClick={()=>run(()=>updateHouseholdTask(t.id,{status:t.status==="DONE"?"OPEN":"DONE"}),t.status==="DONE"?"Task reopened.":"Task completed.")} className="flex w-full items-center justify-between rounded-2xl border border-white/10 p-3 text-left"><span className={t.status==="DONE"?"line-through text-slate-500":""}><b>{t.title}</b><span className="block text-xs text-slate-500">~{t.estimated_minutes} min{t.requires_phone?" · phone":""}{t.requires_computer?" · computer":""}{t.can_multitask?" · multitask":""}</span></span><Check className={cx("h-5 w-5",t.status==="DONE"?"text-emerald-300":"text-slate-700")}/></button>)}</div></Card>:null}

  {tab==="Shopping"?<><Card title="Family Shopping" subtitle="One shared list for groceries and household purchases."><div className="flex gap-2"><input value={shopName} onChange={e=>setShopName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&shopName.trim()&&run(()=>createShoppingItem({household:household.id,name:shopName.trim(),category:"GROCERY"}),"Item added.")} className="h-12 flex-1 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Milk, diapers, protein powder..."/><Btn primary disabled={!shopName.trim()} onClick={()=>run(async()=>{await createShoppingItem({household:household.id,name:shopName.trim(),category:"GROCERY"});setShopName("")},"Item added.")}>Add</Btn></div><div className="mt-4 space-y-2">{shopping.filter(i=>Number(i.household)===Number(household.id)).map(i=><div key={i.id} className="rounded-2xl border border-white/10 p-3"><div className="flex items-center gap-3"><button onClick={()=>run(()=>updateShoppingItem(i.id,{is_checked:!i.is_checked}),i.is_checked?"Item reopened.":"Item checked.")} className={cx("grid h-8 w-8 place-items-center rounded-full border",i.is_checked?"border-emerald-300 bg-emerald-300 text-black":"border-white/20")}><Check className="h-4 w-4"/></button><div className={cx("min-w-0 flex-1 font-black",i.is_checked&&"line-through text-slate-500")}>{i.name}</div></div>{!i.is_checked?<div className="mt-3 grid grid-cols-2 gap-2"><a href={amazonUrl(i.name)} target="_blank" rel="sponsored nofollow noopener noreferrer" className="grid min-h-10 place-items-center rounded-xl border border-amber-300/25 bg-amber-300/10 text-xs font-black text-amber-100">Search Amazon</a><a href={walmartUrl(i.name)} target="_blank" rel="noopener noreferrer" className="grid min-h-10 place-items-center rounded-xl border border-blue-300/25 bg-blue-300/10 text-xs font-black text-blue-100">Search Walmart</a></div>:null}</div>)}</div></Card><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-3 text-xs leading-5 text-slate-400"><b className="text-amber-100">Affiliate disclosure:</b> As an Amazon Associate SyncWorks earns from qualifying purchases. Amazon links only open after you choose them; SyncWorks does not place orders automatically.</div></>:null}

  {tab==="Goals"?<Card title="Daily, Weekly & Monthly Goals" subtitle="Personal or household goals can later feed the SYNC briefing and alert engine."><div className="grid gap-2 sm:grid-cols-[1fr_130px_100px_auto]"><input value={goalForm.title} onChange={e=>setGoalForm(x=>({...x,title:e.target.value}))} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-4" placeholder="Save $1,000 / 4 workouts / meal prep"/><select value={goalForm.cadence} onChange={e=>setGoalForm(x=>({...x,cadence:e.target.value}))} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-3"><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select><input value={goalForm.target_value} onChange={e=>setGoalForm(x=>({...x,target_value:e.target.value}))} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-3"/><Btn primary disabled={!goalForm.title.trim()} onClick={()=>run(()=>createHouseholdGoal({household:household.id,title:goalForm.title,cadence:goalForm.cadence,target_value:goalForm.target_value,unit:goalForm.unit}),"Goal added.")}>Add</Btn></div><div className="mt-4 space-y-2">{goals.filter(g=>Number(g.household)===Number(household.id)).map(g=><button key={g.id} onClick={()=>run(()=>updateHouseholdGoal(g.id,{is_complete:!g.is_complete}),g.is_complete?"Goal reopened.":"Goal completed.")} className="flex w-full items-center justify-between rounded-2xl border border-white/10 p-3 text-left"><span><b className={g.is_complete?"line-through text-slate-500":""}>{g.title}</b><span className="block text-xs text-slate-500">{g.cadence} · {g.current_value}/{g.target_value} {g.unit}</span></span><Check className={cx("h-5 w-5",g.is_complete?"text-emerald-300":"text-slate-700")}/></button>)}</div></Card>:null}

  {tab==="Meals"?<Card title="Meal Schedule" subtitle="Coordinate the household meal plan without replacing each person’s private Nutrition profile."><div className="grid gap-2 sm:grid-cols-[150px_140px_1fr_auto]"><Input label="Date" type="date" value={mealForm.date} onChange={v=>setMealForm(x=>({...x,date:v}))}/><label><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Meal</span><select value={mealForm.meal_type} onChange={e=>setMealForm(x=>({...x,meal_type:e.target.value}))} className="h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-3"><option>BREAKFAST</option><option>LUNCH</option><option>DINNER</option><option>SNACK</option></select></label><Input label="Plan" value={mealForm.title} onChange={v=>setMealForm(x=>({...x,title:v}))} placeholder="Tacos"/><div className="pt-5"><Btn primary disabled={!mealForm.title.trim()} onClick={()=>run(()=>createHouseholdMeal({household:household.id,date:mealForm.date,meal_type:mealForm.meal_type,title:mealForm.title}),"Meal scheduled.")}>Add</Btn></div></div><div className="mt-4 space-y-2">{meals.filter(m=>Number(m.household)===Number(household.id)).map(m=><div key={m.id} className="rounded-2xl border border-white/10 p-3"><b>{m.date} · {m.meal_type}</b><div className="text-sm text-slate-400">{m.title}</div></div>)}</div></Card>:null}

  {tab==="Sharing"?<><Card title="Your Household permissions" subtitle="These are your permissions. Nobody else in the Family can switch on your Finance sharing.">{mySettings?<div className="space-y-2">{[["share_calendar","Family calendar"],["share_tasks","Tasks"],["share_shopping","Shopping"],["share_meals","Meals"],["share_goals","Goals"],["share_finance_summary","Finance summary"],["share_finance_accounts","Financial accounts"],["share_finance_bills","Bills / due dates"],["share_finance_income","Income"],["share_finance_transactions","Transactions"],["share_finance_budgets","Budgets"]].map(([k,l])=><label key={k} className={cx("flex items-center justify-between rounded-2xl border p-3",k.startsWith("share_finance")?"border-amber-300/15 bg-amber-300/[.03]":"border-white/10")}><span><b>{l}</b>{k.startsWith("share_finance")?<span className="block text-xs text-slate-500">Private by default</span>:null}</span><input type="checkbox" checked={!!mySettings[k]} onChange={e=>run(()=>updateHouseholdSettings(mySettings.id,{[k]:e.target.checked}),`${l} sharing updated.`)} className="h-5 w-5"/></label>)}</div>:<p className="text-sm text-slate-500">Your Household sharing profile will appear after membership sync.</p>}</Card><Card title="Availability" subtitle="SYNC can use this later to avoid suggesting tasks you cannot realistically do.">{mySettings?<div className="grid gap-2 sm:grid-cols-3"><select value={mySettings.availability_status} onChange={e=>run(()=>updateHouseholdSettings(mySettings.id,{availability_status:e.target.value}),"Availability updated.")} className="h-12 rounded-2xl border border-white/10 bg-black/20 px-3"><option>AVAILABLE</option><option>BUSY</option><option>AWAY</option><option>DO_NOT_DISTURB</option></select><label className="rounded-2xl border border-white/10 p-3"><input type="checkbox" checked={!!mySettings.phone_available} onChange={e=>run(()=>updateHouseholdSettings(mySettings.id,{phone_available:e.target.checked}),"Phone availability updated.")} className="mr-2"/>Phone available</label><label className="rounded-2xl border border-white/10 p-3"><input type="checkbox" checked={!!mySettings.computer_available} onChange={e=>run(()=>updateHouseholdSettings(mySettings.id,{computer_available:e.target.checked}),"Computer availability updated.")} className="mr-2"/>Computer available</label></div>:null}</Card></>:null}
  </main></div>;
}
