import React, { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import api from "../api/client";
import Button from "../components/ui/Button";
import PMCollectionsAndLeaseRules from "../components/pm/PMCollectionsAndLeaseRules";

const inputClass = "min-h-11 w-full rounded-2xl border border-slate-700 bg-black/35 px-3.5 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-cyan-400/70";
const list = (data) => Array.isArray(data?.results) ? data.results : Array.isArray(data) ? data : [];
const today = new Date().toISOString().slice(0, 10);
const entryTypes = ["CHARGE", "PAYMENT", "CREDIT", "ADJUSTMENT"];
const categories = ["RENT", "LATE_FEE", "SECURITY_DEPOSIT", "UTILITY", "REPAIR", "OTHER"];
const paymentMethods = ["CASH", "CHECK", "ACH", "CARD", "MONEY_ORDER", "HOUSING_AUTHORITY", "OTHER"];
const blankEntry = { tenant: "", entry_date: today, entry_type: "PAYMENT", amount: "", category: "RENT", payment_method: "CASH", reference: "", memo: "" };
const money = (value) => Number(value || 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-300">{label}</span>{children}</label>; }
function errorText(err, fallback) { const data = err?.response?.data; if (data?.detail) return data.detail; if (data && typeof data === "object") return Object.entries(data).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(", ") : value}`).join(" · "); return fallback; }
function Drawer({ title, subtitle, onClose, children, width = "max-w-xl" }) { return <div className="fixed inset-0 z-[220] bg-black/70" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><aside className={`ml-auto h-full w-full ${width} overflow-y-auto border-l border-cyan-500/20 bg-[#050c16] p-5 shadow-2xl`}><div className="flex items-start justify-between gap-4 border-b border-cyan-500/10 pb-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Tenant accounting</div><h2 className="mt-2 text-2xl font-black text-white">{title}</h2>{subtitle ? <p className="mt-1 text-sm text-slate-400">{subtitle}</p> : null}</div><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-3 py-2 text-slate-300">✕</button></div><div className="mt-5">{children}</div></aside></div>; }

export default function PMPayments() {
  const [params, setParams] = useSearchParams();
  const [workspace, setWorkspace] = useState(null);
  const [tenants, setTenants] = useState([]);
  const [entries, setEntries] = useState([]);
  const [billingSummary, setBillingSummary] = useState({ total_due: "0.00", total_past_due: "0.00", past_due_accounts: 0, tenants: [] });
  const [filterTenant, setFilterTenant] = useState(params.get("tenant") || "");
  const [propertyFilter, setPropertyFilter] = useState(params.get("property") || "");
  const [entry, setEntry] = useState({ ...blankEntry, tenant: params.get("tenant") || "" });
  const [editing, setEditing] = useState(null);
  const [selectedIds, setSelectedIds] = useState([]);
  const [drawer, setDrawer] = useState(params.get("add") === "1" ? "entry" : "");
  const [rulesTenant, setRulesTenant] = useState(params.get("tenant") || "");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);

  async function load() { try { setError(""); const ws = await api.get("/pm-hub/workspaces/current/"); setWorkspace(ws.data); const headers = { "X-PM-Workspace-ID": String(ws.data.id) }; const cacheBust = Date.now(); const [tenantResponse, entryResponse, billingResponse] = await Promise.all([api.get(`/pm-hub/tenants/?_=${cacheBust}`, { headers }), api.get(`/pm-hub/ledger/?_=${cacheBust}`, { headers }), api.get(`/pm-hub/billing/summary/?_=${cacheBust}`, { headers })]); setTenants(list(tenantResponse.data)); setEntries(list(entryResponse.data)); setBillingSummary(billingResponse.data || { total_due: "0.00", total_past_due: "0.00", past_due_accounts: 0, tenants: [] }); } catch (err) { setError(errorText(err, "Could not load tenant ledgers.")); } }
  useEffect(() => { load(); }, []);

  const properties = useMemo(() => { const map = new Map(); tenants.forEach((tenant) => { const id = tenant.property_id || tenant.property_name; if (id && !map.has(String(id))) map.set(String(id), { id: String(id), name: tenant.property_name || tenant.property_address || "Property" }); }); return [...map.values()]; }, [tenants]);
  const tenantRows = useMemo(() => tenants.filter((tenant) => !propertyFilter || String(tenant.property_id || tenant.property_name) === String(propertyFilter)), [tenants, propertyFilter]);
  const visibleEntries = useMemo(() => entries.filter((row) => { if (filterTenant && String(row.tenant) !== String(filterTenant)) return false; if (propertyFilter) { const tenant = tenants.find((item) => String(item.id) === String(row.tenant)); if (!tenant || String(tenant.property_id || tenant.property_name) !== String(propertyFilter)) return false; } return true; }), [entries, tenants, filterTenant, propertyFilter]);
  const summaryByTenant = useMemo(() => new Map((billingSummary.tenants || []).map((row) => [String(row.tenant_id), row])), [billingSummary]);
  const allSelected = visibleEntries.length > 0 && visibleEntries.every((row) => selectedIds.includes(row.id));

  function selectTenant(tenantId) { const value = String(tenantId || ""); setFilterTenant(value); setRulesTenant(value); setEntry((current) => ({ ...current, tenant: value })); const next = new URLSearchParams(params); if (value) next.set("tenant", value); else next.delete("tenant"); setParams(next, { replace: true }); }
  function openEntry(tenantId = "") { if (tenantId) selectTenant(tenantId); setEntry({ ...blankEntry, tenant: String(tenantId || filterTenant || "") }); setEditing(null); setDrawer("entry"); }
  function beginEdit(row) { setEditing({ id: row.id, tenant: row.tenant, tenant_name: row.tenant_name, entry_date: row.entry_date, entry_type: row.entry_type, amount: row.amount, category: row.category, payment_method: row.payment_method || "", reference: row.reference || "", memo: row.memo || "" }); setDrawer("edit"); }

  async function saveEntry() { if (!entry.tenant || !entry.amount) return setError("Tenant and amount are required."); setSaving(true); setError(""); try { const headers = { "X-PM-Workspace-ID": String(workspace.id) }; await api.post("/pm-hub/ledger/", { ...entry, payment_method: entry.entry_type === "PAYMENT" ? entry.payment_method : "", workspace_id: workspace.id }, { headers }); setMessage("Ledger entry saved."); setDrawer(""); await load(); selectTenant(entry.tenant); } catch (err) { setError(errorText(err, "Could not save ledger entry.")); } finally { setSaving(false); } }
  async function saveEdit() { if (!editing?.id || !editing.amount) return setError("Amount is required."); setSaving(true); setError(""); try { const headers = { "X-PM-Workspace-ID": String(workspace.id) }; await api.patch(`/pm-hub/ledger/${editing.id}/`, { entry_date: editing.entry_date, entry_type: editing.entry_type, amount: editing.amount, category: editing.category, payment_method: editing.entry_type === "PAYMENT" ? editing.payment_method : "", reference: editing.reference, memo: editing.memo, workspace_id: workspace.id }, { headers }); setMessage("Ledger entry updated."); setDrawer(""); setEditing(null); await load(); } catch (err) { setError(errorText(err, "Could not update the ledger entry.")); } finally { setSaving(false); } }
  async function deleteEntry(row) { if (!window.confirm(`Delete ${row.entry_date} · ${row.category} · ${money(row.amount)}?`)) return; setSaving(true); try { const headers = { "X-PM-Workspace-ID": String(workspace.id) }; await api.delete(`/pm-hub/ledger/${row.id}/`, { headers }); setMessage("Ledger entry deleted."); await load(); } catch (err) { setError(errorText(err, "Could not delete the ledger entry.")); } finally { setSaving(false); } }
  async function deleteSelected() { if (!selectedIds.length || !window.confirm(`Delete ${selectedIds.length} selected ledger item(s)?`)) return; setSaving(true); try { const headers = { "X-PM-Workspace-ID": String(workspace.id) }; await api.post("/pm-hub/ledger/bulk-delete/", { ids: selectedIds, workspace_id: workspace.id }, { headers }); setSelectedIds([]); setMessage("Selected ledger items deleted."); await load(); } catch (err) { setError(errorText(err, "Could not delete selected ledger items.")); } finally { setSaving(false); } }
  function exportCsv() { const rows = [["entry_date", "tenant", "entry_type", "amount", "category", "payment_method", "reference", "memo"], ...visibleEntries.map((row) => [row.entry_date, row.tenant_name, row.entry_type, row.amount, row.category, row.payment_method, row.reference, row.memo])]; const csv = rows.map((row) => row.map((value) => `"${String(value ?? "").replaceAll('"', '""')}"`).join(",")).join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "syncworks-tenant-ledger.csv"; link.click(); URL.revokeObjectURL(url); }

  const form = (model, setter, saveLabel, onSave) => <div className="grid gap-4"><Field label="Tenant"><select className={inputClass} value={model.tenant || ""} onChange={(e) => setter({ ...model, tenant: e.target.value })} disabled={Boolean(model.id)}><option value="">Choose tenant</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.full_name} · {tenant.property_name || "No property"}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Date"><input type="date" className={inputClass} value={model.entry_date || today} onChange={(e) => setter({ ...model, entry_date: e.target.value })} /></Field><Field label="Type"><select className={inputClass} value={model.entry_type} onChange={(e) => setter({ ...model, entry_type: e.target.value })}>{entryTypes.map((value) => <option key={value}>{value}</option>)}</select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Amount"><input inputMode="decimal" className={inputClass} value={model.amount} onChange={(e) => setter({ ...model, amount: e.target.value })} /></Field><Field label="Category"><select className={inputClass} value={model.category} onChange={(e) => setter({ ...model, category: e.target.value })}>{categories.map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></Field></div>{model.entry_type === "PAYMENT" ? <Field label="Payment method"><select className={inputClass} value={model.payment_method || "CASH"} onChange={(e) => setter({ ...model, payment_method: e.target.value })}>{paymentMethods.map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></Field> : null}<Field label="Reference / check number"><input className={inputClass} value={model.reference || ""} onChange={(e) => setter({ ...model, reference: e.target.value })} /></Field><Field label="Memo"><textarea rows="4" className={inputClass} value={model.memo || ""} onChange={(e) => setter({ ...model, memo: e.target.value })} /></Field><Button tone="cyan" onClick={onSave} disabled={saving}>{saving ? "Saving..." : saveLabel}</Button></div>;

  return <div className="min-h-screen bg-transparent text-slate-100"><main className="space-y-5 px-4 py-6 sm:px-6"><section className="rounded-[28px] border border-cyan-500/20 bg-gradient-to-br from-cyan-500/10 via-[#07111f] to-fuchsia-500/10 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Tenant accounting</div><h1 className="mt-2 text-3xl font-black text-white">Ledger Command Center</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Choose the tenant first. Lease rules, collections settings, and entry adjustments stay one click away instead of filling the page.</p></div><div className="flex flex-wrap gap-2"><Button tone="cyan" onClick={() => openEntry(filterTenant)}>+ Add Entry</Button><Button tone="slate" onClick={() => { setRulesTenant(filterTenant || tenantRows[0]?.id || ""); setDrawer("rules"); }}>Lease & Billing Rules</Button></div></div></section>
  {error ? <div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-100">{error}</div> : null}{message ? <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-100">{message}</div> : null}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total Due", billingSummary.total_due, true], ["Past Due", billingSummary.total_past_due, true], ["Past Due Accounts", billingSummary.past_due_accounts, false], ["Tenant Accounts", tenants.length, false]].map(([label, value, isMoney]) => <div key={label} className="rounded-3xl border border-cyan-500/15 bg-[#07111f]/95 p-4"><div className="text-[10px] font-black uppercase tracking-[.18em] text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-white">{isMoney ? money(value) : value || 0}</div></div>)}</div>
  <section className="rounded-[28px] border border-cyan-500/15 bg-[#07111f]/90 p-5"><div className="flex flex-wrap items-end gap-3"><Field label="Property"><select className={inputClass} value={propertyFilter} onChange={(e) => { setPropertyFilter(e.target.value); setFilterTenant(""); }}><option value="">All properties</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name}</option>)}</select></Field><Field label="Tenant"><select className={inputClass} value={filterTenant} onChange={(e) => selectTenant(e.target.value)}><option value="">All tenants</option>{tenantRows.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.full_name}{tenant.status === "INACTIVE" ? " · Former" : ""}</option>)}</select></Field><Button tone="slate" onClick={exportCsv}>Export visible</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{tenantRows.map((tenant) => { const account = summaryByTenant.get(String(tenant.id)) || {}; const active = String(filterTenant) === String(tenant.id); return <button key={tenant.id} type="button" onClick={() => selectTenant(tenant.id)} className={`rounded-2xl border p-4 text-left ${active ? "border-cyan-400/50 bg-cyan-500/10" : "border-slate-800 bg-black/20 hover:border-cyan-400/25"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-black text-white">{tenant.full_name}</div><div className="mt-1 text-xs text-slate-500">{tenant.property_name || "No property"} · {tenant.unit_label || "No unit"}</div></div><span className={`rounded-full border px-2 py-1 text-[9px] font-black ${tenant.status === "INACTIVE" ? "border-amber-400/30 text-amber-200" : "border-emerald-400/30 text-emerald-200"}`}>{tenant.status === "INACTIVE" ? "FORMER" : "CURRENT"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-black/30 p-3 text-slate-500">Balance<div className="mt-1 text-lg font-black text-white">{money(account.amount_due ?? tenant.balance)}</div></div><div className="rounded-xl bg-black/30 p-3 text-slate-500">Past due<div className="mt-1 text-lg font-black text-rose-200">{money(account.past_due)}</div></div></div></button>; })}</div></section>
  <section className="rounded-[28px] border border-cyan-500/15 bg-[#07111f]/90 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">{filterTenant ? `${tenants.find((tenant) => String(tenant.id) === String(filterTenant))?.full_name || "Tenant"} ledger` : "Visible ledger"}</h2><p className="mt-1 text-xs text-slate-500">Use a tenant card to focus the ledger. Editing and billing rules open in drawers.</p></div><div className="flex gap-2"><Button tone="cyan" onClick={() => openEntry(filterTenant)}>+ Add Entry</Button>{filterTenant ? <Button tone="slate" onClick={() => { setRulesTenant(filterTenant); setDrawer("rules"); }}>Lease Rules</Button> : null}</div></div><div className="mt-4 flex flex-wrap items-center gap-3 rounded-2xl border border-slate-800 bg-black/20 p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={allSelected} onChange={() => setSelectedIds(allSelected ? [] : visibleEntries.map((row) => row.id))} />Select all visible</label><span className="text-xs text-slate-500">{selectedIds.length} selected</span><button className="rounded-xl border border-rose-400/30 px-3 py-2 text-xs font-black text-rose-100 disabled:opacity-40" disabled={!selectedIds.length || saving} onClick={deleteSelected}>Delete selected</button></div><div className="mt-4 space-y-3">{visibleEntries.map((row) => <article key={row.id} className="rounded-2xl border border-slate-800 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><label className="flex items-start gap-3"><input className="mt-1" type="checkbox" checked={selectedIds.includes(row.id)} onChange={() => setSelectedIds((current) => current.includes(row.id) ? current.filter((id) => id !== row.id) : [...current, row.id])} /><span><span className="block text-sm font-black text-white">{row.tenant_name}</span><span className="block text-xs text-slate-400">{row.entry_date} · {String(row.category).replaceAll("_", " ")} · {row.entry_type}</span>{row.memo ? <span className="mt-1 block text-xs text-slate-500">{row.memo}</span> : null}</span></label><div className="text-right"><div className={`font-black ${["PAYMENT", "CREDIT"].includes(row.entry_type) ? "text-emerald-300" : "text-rose-200"}`}>{["PAYMENT", "CREDIT"].includes(row.entry_type) ? "−" : "+"}{money(row.amount)}</div><div className="mt-2 flex gap-2"><button className="rounded-xl border border-cyan-400/30 px-3 py-2 text-xs font-bold text-cyan-100" onClick={() => beginEdit(row)}>Edit</button><button className="rounded-xl border border-rose-400/30 px-3 py-2 text-xs font-bold text-rose-100" onClick={() => deleteEntry(row)}>Delete</button></div></div></div></article>)}</div>{!visibleEntries.length ? <div className="py-12 text-center text-sm text-slate-500">No ledger entries match this tenant/property selection.</div> : null}</section></main>
  {drawer === "entry" ? <Drawer title="Add ledger entry" subtitle="Quickly post a charge, payment, credit, adjustment, or deposit item." onClose={() => setDrawer("")}>{form(entry, setEntry, "Save Entry", saveEntry)}</Drawer> : null}
  {drawer === "edit" && editing ? <Drawer title="Edit ledger entry" subtitle={editing.tenant_name} onClose={() => { setDrawer(""); setEditing(null); }}>{form(editing, setEditing, "Save Changes", saveEdit)}</Drawer> : null}
  {drawer === "rules" ? <Drawer title="Lease & Billing Rules" subtitle="Automatic rent, late-fee, payment-arrangement, eviction, collections, and deposit settings." width="max-w-3xl" onClose={() => setDrawer("")}><Field label="Tenant account"><select className={inputClass} value={rulesTenant} onChange={(e) => setRulesTenant(e.target.value)}><option value="">Choose tenant</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.full_name} · {tenant.property_name || "No property"}</option>)}</select></Field><div className="mt-5">{rulesTenant ? <PMCollectionsAndLeaseRules workspace={workspace} tenantId={rulesTenant} onRefresh={load} /> : <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">Choose a tenant to edit lease and billing rules.</div>}</div></Drawer> : null}</div>;
}
